package postgres

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/admin/core"
)

// BackupDestination store implementation (Story 3.2, FR-29/AD-15): CRUD over
// the Admin-owned multi-row backup_destinations table. The credential COALESCE
// keep-existing lives inside the single UPDATE statement, so it is atomic with
// the write (no read-then-write race).

// ListBackupDestinations reads every destination, oldest first (GET_LIST).
func (r *Repository) ListBackupDestinations(ctx context.Context) ([]*core.BackupDestination, error) {
	rows, err := r.queries.ListBackupDestinations(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*core.BackupDestination, 0, len(rows))
	for i := range rows {
		out = append(out, backupDestinationFromRow(rows[i]))
	}
	return out, nil
}

// GetBackupDestination reads one destination by id (for update/test/delete).
// Returns nil, nil when no row matches.
func (r *Repository) GetBackupDestination(ctx context.Context, id string) (*core.BackupDestination, error) {
	uid, err := parseBackupDestinationID(id)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.GetBackupDestination(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return backupDestinationFromRow(row), nil
}

// CreateBackupDestination inserts a destination and returns the resulting row
// (CREATE_VALID). The id is generated by the DB (uuidv7).
func (r *Repository) CreateBackupDestination(ctx context.Context, dest *core.BackupDestination) (*core.BackupDestination, error) {
	row, err := r.queries.CreateBackupDestination(ctx, CreateBackupDestinationParams{
		Name:              dest.Name,
		Mechanism:         dest.Mechanism,
		Endpoint:          dest.Endpoint,
		BucketOrPath:      dest.BucketOrPath,
		Username:          dest.Username,
		PasswordEncrypted: dest.PasswordEncrypted,
		Column7:           dest.Schedule,
	})
	if err != nil {
		return nil, err
	}
	return backupDestinationFromRow(row), nil
}

// UpdateBackupDestination replaces one destination's values and returns the
// resulting row (UPDATE_KEEP_CREDENTIAL). An empty dest.PasswordEncrypted KEEPS
// the existing ciphertext inside the single UPDATE (COALESCE on the RHS reading
// the pre-update column value), so keep-existing is atomic; dest.ClearCredential
// WIPES the stored credential (explicit revoke, finding). Returns
// core.ErrBackupDestinationNotFound when the id does not exist.
func (r *Repository) UpdateBackupDestination(ctx context.Context, dest *core.BackupDestination) (*core.BackupDestination, error) {
	uid, err := parseBackupDestinationID(dest.ID)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.UpdateBackupDestination(ctx, UpdateBackupDestinationParams{
		ID:                uid,
		Name:              dest.Name,
		Mechanism:         dest.Mechanism,
		Endpoint:          dest.Endpoint,
		BucketOrPath:      dest.BucketOrPath,
		Username:          dest.Username,
		Column7:           dest.Schedule,
		PasswordEncrypted: dest.PasswordEncrypted,
		ClearCredential:   dest.ClearCredential,
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrBackupDestinationNotFound
	}
	if err != nil {
		return nil, err
	}
	return backupDestinationFromRow(row), nil
}

// DeleteBackupDestination removes one destination (DELETE). Returns
// core.ErrBackupDestinationNotFound when the id does not exist.
func (r *Repository) DeleteBackupDestination(ctx context.Context, id string) error {
	uid, err := parseBackupDestinationID(id)
	if err != nil {
		return err
	}
	n, err := r.queries.DeleteBackupDestination(ctx, uid)
	if err != nil {
		return err
	}
	if n == 0 {
		return core.ErrBackupDestinationNotFound
	}
	return nil
}

// backupDestinationFromRow maps an sqlc backup_destinations row to the domain
// destination. The schedule NULL is mapped to "" (optional hint unset).
func backupDestinationFromRow(row BackupDestination) *core.BackupDestination {
	schedule := ""
	if row.Schedule.Valid {
		schedule = row.Schedule.String
	}
	return &core.BackupDestination{
		ID:                row.ID.String(),
		Name:              row.Name,
		Mechanism:         row.Mechanism,
		Endpoint:          row.Endpoint,
		BucketOrPath:      row.BucketOrPath,
		Username:          row.Username,
		PasswordEncrypted: row.PasswordEncrypted,
		Schedule:          schedule,
		CreatedAt:         row.CreatedAt.Time,
		UpdatedAt:         row.UpdatedAt.Time,
	}
}

// parseBackupDestinationID parses a URL-path uuidv7 into pgtype.UUID. A
// malformed id is treated as not-found (no existence hint to a caller).
func parseBackupDestinationID(id string) (pgtype.UUID, error) {
	var uid pgtype.UUID
	if err := uid.Scan(id); err != nil {
		return pgtype.UUID{}, core.ErrBackupDestinationNotFound
	}
	return uid, nil
}