// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
)

const getSmtpSettings = `-- name: GetSmtpSettings :many

SELECT id, host, port, security, sender_address, sender_name, username, password_encrypted, created_at, updated_at
FROM smtp_settings
ORDER BY created_at ASC
LIMIT 1
`

// Admin module store (AD-1/AD-11), generated into package postgres by sqlc.
// Story 3.1 ships the SMTP-settings queries for the Admin-owned
// `smtp_settings` single-row table (FR-28/AD-14); later Epic 3 stories extend
// this file (backup_destinations, schedules) and re-run `just sqlc-generate`.
// The single SMTP-settings row (the partial unique index guarantees at most
// one). Zero rows = "not configured yet" → the consumer returns zero defaults.
// The encrypted password column is intentionally selected: decryption happens
// only in the sender/test-send path, in memory (NFR-S4) — it is never
// serialized by the HTTP surface.
func (q *Queries) GetSmtpSettings(ctx context.Context) ([]SmtpSetting, error) {
	rows, err := q.db.Query(ctx, getSmtpSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmtpSetting
	for rows.Next() {
		var i SmtpSetting
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.Security,
			&i.SenderAddress,
			&i.SenderName,
			&i.Username,
			&i.PasswordEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSmtpSettings = `-- name: InsertSmtpSettings :exec
INSERT INTO smtp_settings (host, port, security, sender_address, sender_name, username, password_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE(NULLIF($7::text, ''), ''))
ON CONFLICT DO NOTHING
`

type InsertSmtpSettingsParams struct {
	Host              string `json:"host"`
	Port              int32  `json:"port"`
	Security          string `json:"security"`
	SenderAddress     string `json:"sender_address"`
	SenderName        string `json:"sender_name"`
	Username          string `json:"username"`
	PasswordEncrypted string `json:"password_encrypted"`
}

// First-time write of the settings row. ON CONFLICT DO NOTHING absorbs the
// lost race of two concurrent first writes (the single-row partial index lets
// only one INSERT land; the repository re-applies its values via a follow-up
// UPDATE so no write is silently dropped). An empty password stores the empty
// default (no-auth relay); keep-existing is a no-op on the very first write.
func (q *Queries) InsertSmtpSettings(ctx context.Context, arg InsertSmtpSettingsParams) error {
	_, err := q.db.Exec(ctx, insertSmtpSettings,
		arg.Host,
		arg.Port,
		arg.Security,
		arg.SenderAddress,
		arg.SenderName,
		arg.Username,
		arg.PasswordEncrypted,
	)
	return err
}

const updateSmtpSettings = `-- name: UpdateSmtpSettings :execrows
UPDATE smtp_settings
SET host = $1,
    port = $2,
    security = $3,
    sender_address = $4,
    sender_name = $5,
    username = $6,
    password_encrypted = COALESCE(NULLIF($7::text, ''), password_encrypted),
    updated_at = now()
WHERE id = (SELECT id FROM smtp_settings ORDER BY created_at ASC LIMIT 1)
`

type UpdateSmtpSettingsParams struct {
	Host              string `json:"host"`
	Port              int32  `json:"port"`
	Security          string `json:"security"`
	SenderAddress     string `json:"sender_address"`
	SenderName        string `json:"sender_name"`
	Username          string `json:"username"`
	PasswordEncrypted string `json:"password_encrypted"`
}

// Replace the single settings row's values (zero rows when none exists yet —
// the repository inserts in that case). The password is COALESCED: an empty
// value KEEPS the existing ciphertext, a non-empty one replaces it — both in
// the SAME statement (the RHS reads the pre-update row value atomically), so
// keep-existing is atomic (no read-then-write race a concurrent update could
// exploit).
func (q *Queries) UpdateSmtpSettings(ctx context.Context, arg UpdateSmtpSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSmtpSettings,
		arg.Host,
		arg.Port,
		arg.Security,
		arg.SenderAddress,
		arg.SenderName,
		arg.Username,
		arg.PasswordEncrypted,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
