package postgres

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/admin/core"
)

// Schedules store implementation (Story 4.1, FR-30/AD-16): list-active /
// create / update / archive over the Admin-owned schedules table. Soft archive
// only — no DELETE endpoint, no hard delete (FK history preserved). The
// `archived_at IS NULL` guard on update/archive makes an already-archived row
// non-existent to the surface (ErrScheduleNotFound).

// ListSchedules reads the ACTIVE catalog in a deterministic order (GET_LIST).
// Archived rows (archived_at IS NOT NULL) never appear.
func (r *Repository) ListSchedules(ctx context.Context) ([]*core.Schedule, error) {
	rows, err := r.queries.ListSchedules(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*core.Schedule, 0, len(rows))
	for i := range rows {
		out = append(out, scheduleFromRow(rows[i]))
	}
	return out, nil
}

// CreateSchedule inserts a schedule and returns the resulting row
// (CREATE_VALID). The id is generated by the DB (uuidv7); the reserved
// weekday/time columns stay NULL. A name already held by an ARCHIVED row (the
// active-catalog guard cannot see it, but the DB's UNIQUE name constraint is
// the backstop) surfaces as the German duplicate-name 400 — never a 500.
func (r *Repository) CreateSchedule(ctx context.Context, schedule *core.Schedule) (*core.Schedule, error) {
	row, err := r.queries.CreateSchedule(ctx, CreateScheduleParams{
		Name:              schedule.Name,
		IntervalUnit:      schedule.IntervalUnit,
		IntervalMagnitude: int32(schedule.IntervalMagnitude),
	})
	if isUniqueViolation(err) {
		return nil, &core.InvalidSchedulesError{Message: core.MsgScheduleNameTaken}
	}
	if err != nil {
		return nil, err
	}
	return scheduleFromRow(row), nil
}

// UpdateSchedule replaces one ACTIVE schedule's name/interval and refreshes
// updated_at (UPDATE_VALID). Returns core.ErrScheduleNotFound when the id does
// not exist OR the row is already archived (the SQL's `archived_at IS NULL`
// guard affects zero rows then). A new name already held by an ARCHIVED row
// (invisible to the core's active-only uniqueness guard) trips the DB UNIQUE
// constraint and is mapped to the German duplicate-name 400 — never a raw 500.
func (r *Repository) UpdateSchedule(ctx context.Context, schedule *core.Schedule) (*core.Schedule, error) {
	uid, err := parseScheduleID(schedule.ID)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.UpdateSchedule(ctx, UpdateScheduleParams{
		ID:                uid,
		Name:              schedule.Name,
		IntervalUnit:      schedule.IntervalUnit,
		IntervalMagnitude: int32(schedule.IntervalMagnitude),
	})
	if isUniqueViolation(err) {
		return nil, &core.InvalidSchedulesError{Message: core.MsgScheduleNameTaken}
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrScheduleNotFound
	}
	if err != nil {
		return nil, err
	}
	return scheduleFromRow(row), nil
}

// ArchiveSchedule soft-archives one schedule (ARCHIVE): archived_at is set, the
// row leaves the active list. Returns core.ErrScheduleNotFound when the id does
// not exist OR the row is already archived (ARCHIVE_ARCHIVED → 404 sentinel).
func (r *Repository) ArchiveSchedule(ctx context.Context, id string) (*core.Schedule, error) {
	uid, err := parseScheduleID(id)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.ArchiveSchedule(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrScheduleNotFound
	}
	if err != nil {
		return nil, err
	}
	return scheduleFromRow(row), nil
}

// scheduleFromRow maps an sqlc schedules row to the domain schedule. The
// reserved weekday_set (nil when NULL) and time_of_day (nil when NULL) are
// carried through for completeness — they are always NULL in V1. ArchivedAt is
// nil for an active row, set after soft-archive.
func scheduleFromRow(row Schedule) *core.Schedule {
	var timeOfDay *string
	if row.TimeOfDay.Valid {
		t := time.Unix(0, 0).UTC().Add(time.Duration(row.TimeOfDay.Microseconds) * time.Microsecond)
		formatted := t.Format("15:04:05")
		timeOfDay = &formatted
	}
	var archivedAt *time.Time
	if row.ArchivedAt.Valid {
		t := row.ArchivedAt.Time
		archivedAt = &t
	}
	return &core.Schedule{
		ID:                row.ID.String(),
		Name:              row.Name,
		IntervalUnit:      row.IntervalUnit,
		IntervalMagnitude: int(row.IntervalMagnitude),
		WeekdaySet:        row.WeekdaySet,
		TimeOfDay:         timeOfDay,
		ArchivedAt:        archivedAt,
		CreatedAt:         row.CreatedAt.Time,
		UpdatedAt:         row.UpdatedAt.Time,
	}
}

// parseScheduleID parses a URL-path uuidv7 into pgtype.UUID. A malformed id is
// treated as not-found (no existence hint to a caller).
func parseScheduleID(id string) (pgtype.UUID, error) {
	var uid pgtype.UUID
	if err := uid.Scan(id); err != nil {
		return pgtype.UUID{}, core.ErrScheduleNotFound
	}
	return uid, nil
}

// isUniqueViolation reports whether err is a PostgreSQL unique-constraint
// violation (SQLSTATE 23505) — e.g. the schedules.name UNIQUE constraint.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}
