package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/platform/pguuid"
	"github.com/saskia-peters/gear/internal/tools/core"
)

// Inspection store implementation (Story 5.3, FR-12/FR-13/FR-14/AD-4/AD-5):
// the transactional inspection+items insert and the derived-status input read
// over the Tool-owned inspections + inspection_items + reinstatements tables
// (migration 000027). Records are append-only — an inspection is immutable
// once persisted (the history surface, FR-18, reads them; there is no update
// path). The reinstatement WRITE path is Story 5.6; this store only CONSULTS
// the table for the clock anchor.

// InsertInspection persists one inspection AND its snapshot items in ONE
// transaction (the Story 2.5 lesson): the inspection row first, then each item
// (label + position snapshotted by the core from the type's checklist). A
// failed item write rolls the whole inspection back — a half-persisted record
// never exists. The ids are generated by the DB (uuidv7); submitted_at is the
// DB now(). Returns the persisted record with its ordered items re-read so the
// response round-trips exactly what the DB holds.
//
// ATOMICITY is at-most-once (Story 7.5, NFR-R1): the CLIENT-SUPPLIED
// idempotency_key is inserted with the row and the DB UNIQUE (tool_id,
// idempotency_key) constraint is the authority. A retried insert of an
// already-committed record (or a CONCURRENT_RACE where the two inserts race)
// is absorbed by `ON CONFLICT DO NOTHING` → zero rows → the repository REPLAYS
// the already-persisted record (row + its items, fetched within the same
// transaction) instead of erroring — the client sees the same committed result.
// The returned `replayed` flag is true when the insert was ABSORBED (a
// retry/race was deduped by the constraint and the winner's row replayed) —
// the core must not re-audit such a write.
func (r *Repository) InsertInspection(ctx context.Context, inspection *core.Inspection, idempotencyKey string) (*core.Inspection, bool, error) {
	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, false, err
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after Commit

	q := r.queries.WithTx(tx)

	toolID, err := parseOptionalUUID(inspection.ToolID)
	if err != nil {
		return nil, false, err
	}
	inspectorID, err := parseOptionalUUID(inspection.InspectorID)
	if err != nil {
		return nil, false, err
	}
	key, err := parseIdempotencyKey(idempotencyKey)
	if err != nil {
		return nil, false, err
	}
	row, err := q.InsertInspection(ctx, InsertInspectionParams{
		ToolID:         toolID,
		InspectorID:    inspectorID,
		Mode:           inspection.Mode,
		OverallResult:  inspection.OverallResult,
		Notes:          inspectionNotesValue(inspection.Notes),
		IdempotencyKey: key,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// The unique constraint absorbed the duplicate (a retried submit or a
			// CONCURRENT_RACE — Story 7.5): replay the already-persisted record
			// (row + its items, re-read through the SAME transaction) so the
			// response round-trips exactly what the DB holds. Never an error,
			// never a second row. `replayed=true` so the core never re-audits a
			// write it did not perform.
			existing, ferr := q.FindInspectionByToolAndKey(ctx, FindInspectionByToolAndKeyParams{
				ToolID:         toolID,
				IdempotencyKey: key,
			})
			if ferr != nil {
				return nil, false, ferr
			}
			itemRows, ferr := q.GetInspectionItems(ctx, existing.ID)
			if ferr != nil {
				return nil, false, ferr
			}
			if err := tx.Commit(ctx); err != nil {
				return nil, false, err
			}
			return inspectionFromRow(existing, itemRows), true, nil
		}
		return nil, false, err
	}

	for _, item := range inspection.Items {
		itemID, err := parseOptionalUUID(item.ItemID)
		if err != nil {
			return nil, false, err
		}
		if err := q.InsertInspectionItem(ctx, InsertInspectionItemParams{
			InspectionID: row.ID,
			ItemID:       itemID,
			Label:        item.Label,
			Position:     int32(item.Position),
			Result:       item.Result,
		}); err != nil {
			return nil, false, err
		}
	}

	// Re-read the snapshotted items THROUGH the transaction's queries BEFORE
	// committing: a re-read failure here returns a 500 while the record is not
	// yet committed — it must never surface an error AFTER the commit (an
	// already-committed record would be invisible to a client retry and the
	// response would fail for nothing).
	itemRows, err := q.GetInspectionItems(ctx, row.ID)
	if err != nil {
		return nil, false, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, false, err
	}
	return inspectionFromRow(row, itemRows), false, nil
}

// GetToolInspectionStatus is the derived-status input read (Story 5.3,
// AD-4/AD-5): the LATEST FAILED inspection's submitted_at (the OOS anchor — a
// PASS inspection does NOT clear it), the LATEST PASSING inspection's
// submitted_at and the LATEST reinstatement's created_at. A tool with no
// records at all maps to a nil-safe status (never-inspected → the derivation
// answers `red`); a malformed tool id answers core.ErrToolNotFound.
func (r *Repository) GetToolInspectionStatus(ctx context.Context, toolID string) (*core.ToolInspectionStatus, error) {
	uid, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}

	status := &core.ToolInspectionStatus{}

	latestFail, err := r.queries.GetLatestFailedInspection(ctx, uid)
	switch {
	case err == nil:
		if latestFail.Valid {
			t := latestFail.Time
			status.LatestFailAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
		// Never failed: LatestFailAt stays nil (the derivation handles it).
	default:
		return nil, err
	}

	lastSuccess, err := r.queries.GetLatestPassInspection(ctx, uid)
	switch {
	case err == nil:
		if lastSuccess.Valid {
			t := lastSuccess.Time
			status.LastSuccessAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
	default:
		return nil, err
	}

	lastReinstatement, err := r.queries.GetLatestReinstatement(ctx, uid)
	switch {
	case err == nil:
		if lastReinstatement.Valid {
			t := lastReinstatement.Time
			status.LastReinstatedAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
	default:
		return nil, err
	}

	return status, nil
}

// FindInspectionByToolAndKey is the EARLY replay lookup (Story 7.5): given a
// tool + the client-supplied idempotency key, it returns the EXISTING record
// WITH its ordered snapshot items, or (nil, nil) when no record matches. The
// core calls it right after the permission gate + tool load, BEFORE the
// OOS/qualification gates, so a retried submit of an already-committed FAIL
// inspection (the tool is now OOS) replays 200 instead of the OOS 403. A
// malformed tool id answers core.ErrToolNotFound (the core's tool load already
// ran first, so this is only reachable with a valid id).
func (r *Repository) FindInspectionByToolAndKey(ctx context.Context, toolID, idempotencyKey string) (*core.Inspection, error) {
	tool, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}
	key, err := parseIdempotencyKey(idempotencyKey)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.FindInspectionByToolAndKey(ctx, FindInspectionByToolAndKeyParams{
		ToolID:         tool,
		IdempotencyKey: key,
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	itemRows, err := r.queries.GetInspectionItems(ctx, row.ID)
	if err != nil {
		return nil, err
	}
	return inspectionFromRow(row, itemRows), nil
}

// FindReinstatementByToolAndKey is the EARLY replay lookup for the
// reinstatement write (Story 7.5): given a tool + the client-supplied
// idempotency key, it returns the EXISTING reinstatement, or (nil, nil) when
// no record matches. The core calls it right after the permission gate + tool
// load, BEFORE the OOS precondition, so a retried reinstate of an
// already-committed row (which flipped the tool serviceable — the NOT-OOS 400
// would otherwise reject it) replays 200 instead. A malformed tool id answers
// core.ErrToolNotFound.
func (r *Repository) FindReinstatementByToolAndKey(ctx context.Context, toolID, idempotencyKey string) (*core.Reinstatement, error) {
	tool, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}
	key, err := parseIdempotencyKey(idempotencyKey)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.FindReinstatementByToolAndKey(ctx, FindReinstatementByToolAndKeyParams{
		ToolID:         tool,
		IdempotencyKey: key,
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return reinstatementFromRow(row), nil
}

// InsertReinstatement persists one reinstatement row (Story 5.6, FR-15/AD-9):
// a single transaction-free insert — the reinstatement is append-only and has
// no dependent rows. The ids are generated by the DB (uuidv7); created_at is
// the DB now(). The core validated the reason before this is called.
//
// ATOMICITY is at-most-once (Story 7.5, NFR-R1): the CLIENT-SUPPLIED
// idempotency_key rides on the row; the DB UNIQUE (tool_id, idempotency_key)
// constraint absorbs a retried / concurrently-racing duplicate
// (`ON CONFLICT DO NOTHING` → zero rows). An ABSORBED duplicate returns the
// already-persisted row + `replayed=true` — never an error, never a second row
// — so the core can distinguish replay from fresh and never re-audit a write
// it did not perform.
func (r *Repository) InsertReinstatement(ctx context.Context, toolID, actorID, reason, idempotencyKey string) (*core.Reinstatement, bool, error) {
	tool, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, false, err
	}
	actor, err := parseOptionalUUID(actorID)
	if err != nil {
		return nil, false, err
	}
	key, err := parseIdempotencyKey(idempotencyKey)
	if err != nil {
		return nil, false, err
	}
	row, err := r.queries.InsertReinstatement(ctx, InsertReinstatementParams{
		ToolID:         tool,
		ActorID:        actor,
		Reason:         reason,
		IdempotencyKey: key,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// A retried reinstate or a CONCURRENT_RACE (Story 7.5): the unique
			// constraint absorbed the duplicate — return the already-persisted
			// row + the replay signal, never an error.
			existing, ferr := r.queries.FindReinstatementByToolAndKey(ctx, FindReinstatementByToolAndKeyParams{
				ToolID:         tool,
				IdempotencyKey: key,
			})
			if ferr != nil {
				return nil, false, ferr
			}
			return reinstatementFromRow(existing), true, nil
		}
		return nil, false, err
	}
	return reinstatementFromRow(row), false, nil
}

// GetLatestInspectionByTool reads the LATEST inspection of a tool (ANY result —
// Story 6.2, FR-17): the status report's "Zuletzt geprüft" + "Prüfer/in"
// inputs. The submitted_at DESC, id DESC tiebreak is deterministic (the 000027
// index inspections_tool_id_submitted_at_idx serves it). A malformed tool id
// answers core.ErrToolNotFound; a tool with no inspections answers (nil, nil) —
// the report renders "–".
func (r *Repository) GetLatestInspectionByTool(ctx context.Context, toolID string) (*core.LatestInspection, error) {
	uid, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.GetLatestInspectionByTool(ctx, uid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return &core.LatestInspection{
		SubmittedAt: row.SubmittedAt.Time,
		InspectorID: row.InspectorID.String(),
	}, nil
}

// ListInspectionsByTool reads the FULL inspection history of a tool (Story 6.3,
// FR-18): every row reverse-chronological (submitted_at DESC, id DESC — the SQL
// ORDER BY guarantees it) EACH WITH its snapshotted ordered checklist items. The
// items are fetched in ONE round-trip (ListInspectionItemsByTool JOINs
// inspections by tool_id) and grouped onto the inspections — never an N+1
// per-inspection item read. A malformed tool id answers core.ErrToolNotFound.
// A tool with no inspections answers an empty list, nil-safe.
func (r *Repository) ListInspectionsByTool(ctx context.Context, toolID string) ([]*core.Inspection, error) {
	uid, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}
	rows, err := r.queries.ListInspectionsByTool(ctx, uid)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Inspection{}, nil
	}
	itemRows, err := r.queries.ListInspectionItemsByTool(ctx, uid)
	if err != nil {
		return nil, err
	}
	itemsByInspection := groupInspectionItems(itemRows)
	out := make([]*core.Inspection, 0, len(rows))
	for _, row := range rows {
		out = append(out, inspectionFromRow(row, itemsByInspection[row.ID]))
	}
	return out, nil
}

// ListReinstatementsByTool reads the FULL reinstatement ledger of a tool (Story
// 6.3, FR-18): every row newest first (created_at DESC, id DESC — the SQL ORDER
// BY guarantees it). A malformed tool id answers core.ErrToolNotFound. A tool
// with no reinstatements answers an empty list, nil-safe.
func (r *Repository) ListReinstatementsByTool(ctx context.Context, toolID string) ([]*core.Reinstatement, error) {
	uid, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}
	rows, err := r.queries.ListReinstatementsByTool(ctx, uid)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Reinstatement{}, nil
	}
	out := make([]*core.Reinstatement, 0, len(rows))
	for _, row := range rows {
		out = append(out, reinstatementFromRow(row))
	}
	return out, nil
}

// ListInspectionsByInspector reads every inspection the user performed as
// inspector (Story 3.3 DSGVO export, FR-24): every row reverse-chronological
// (submitted_at DESC, id DESC — the 000029 index
// inspections_inspector_id_idx serves it), EACH WITH its snapshotted ordered
// checklist items. The items are fetched in ONE round-trip
// (ListInspectionItemsByInspector JOINs inspections by inspector_id) and
// grouped onto the inspections — never an N+1 per-inspection item read,
// mirroring the per-tool history surface. A user with no inspections answers
// an empty list, nil-safe.
func (r *Repository) ListInspectionsByInspector(ctx context.Context, userID string) ([]*core.Inspection, error) {
	uid, err := parseOptionalUUID(userID)
	if err != nil {
		return nil, err
	}
	rows, err := r.queries.ListInspectionsByInspector(ctx, uid)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Inspection{}, nil
	}
	itemRows, err := r.queries.ListInspectionItemsByInspector(ctx, uid)
	if err != nil {
		return nil, err
	}
	itemsByInspection := groupInspectionItems(itemRows)
	out := make([]*core.Inspection, 0, len(rows))
	for _, row := range rows {
		out = append(out, inspectionFromRow(row, itemsByInspection[row.ID]))
	}
	return out, nil
}

// ListReinstatementsByActor reads every reinstatement the user performed as
// actor (Story 3.3 DSGVO export, FR-24): every row newest first (created_at
// DESC, id DESC — the 000029 index reinstatements_actor_id_idx serves it). A
// user with no reinstatements answers an empty list, nil-safe.
func (r *Repository) ListReinstatementsByActor(ctx context.Context, userID string) ([]*core.Reinstatement, error) {
	uid, err := parseOptionalUUID(userID)
	if err != nil {
		return nil, err
	}
	rows, err := r.queries.ListReinstatementsByActor(ctx, uid)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Reinstatement{}, nil
	}
	out := make([]*core.Reinstatement, 0, len(rows))
	for _, row := range rows {
		out = append(out, reinstatementFromRow(row))
	}
	return out, nil
}

// groupInspectionItems buckets the fetched item rows by their inspection_id so
// the repository can attach them to the fetched inspections in one round-trip.
func groupInspectionItems(rows []InspectionItem) map[pgtype.UUID][]InspectionItem {
	grouped := make(map[pgtype.UUID][]InspectionItem, len(rows))
	for i := range rows {
		id := rows[i].InspectionID
		grouped[id] = append(grouped[id], rows[i])
	}
	return grouped
}

// reinstatementFromRow maps an sqlc reinstatement row to the domain value.
func reinstatementFromRow(row Reinstatement) *core.Reinstatement {
	return &core.Reinstatement{
		ID:        row.ID.String(),
		ToolID:    row.ToolID.String(),
		ActorID:   row.ActorID.String(),
		Reason:    row.Reason,
		CreatedAt: row.CreatedAt.Time,
	}
}

// inspectionNotesValue encodes the notes for the nullable text column: an empty
// note (the common case) stores SQL NULL, a non-empty one the text.
func inspectionNotesValue(notes string) pgtype.Text {
	if notes == "" {
		return pgtype.Text{}
	}
	return pgtype.Text{String: notes, Valid: true}
}

// parseIdempotencyKey parses the CLIENT-SUPPLIED idempotency key (Story 7.5,
// NFR-R1): the HTTP layer already validated the canonical UUID form, so a
// malformed key reaching the store is a defense-in-depth failure — surfaced as
// an internal error, NEVER the 404 sentinel (a key is not a tool id). The
// shared parse contract lives in platform/pguuid (Epic 4 retro item D1).
func parseIdempotencyKey(key string) (pgtype.UUID, error) {
	uid, err := pguuid.ParseOptional(key)
	if err != nil {
		return pgtype.UUID{}, fmt.Errorf("tools postgres: malformed idempotency key: %w", err)
	}
	return uid, nil
}

// inspectionFromRow maps an sqlc inspection row (+ its ordered snapshot items)
// to the domain value. A NULL notes column reads back as "".
func inspectionFromRow(row Inspection, itemRows []InspectionItem) *core.Inspection {
	return &core.Inspection{
		ID:             row.ID.String(),
		ToolID:         row.ToolID.String(),
		InspectorID:    row.InspectorID.String(),
		Mode:           row.Mode,
		OverallResult:  row.OverallResult,
		Notes:          row.Notes.String,
		IdempotencyKey: row.IdempotencyKey.String(),
		SubmittedAt:    row.SubmittedAt.Time,
		Items:          inspectionItemsFromRows(itemRows),
	}
}

// inspectionItemsFromRows maps the ordered snapshot rows to the domain items
// (already ordered by position — the SQL ORDER BY guarantees it).
func inspectionItemsFromRows(rows []InspectionItem) []core.InspectionItem {
	if len(rows) == 0 {
		return []core.InspectionItem{}
	}
	items := make([]core.InspectionItem, 0, len(rows))
	for _, row := range rows {
		items = append(items, core.InspectionItem{
			ID:           row.ID.String(),
			InspectionID: row.InspectionID.String(),
			ItemID:       row.ItemID.String(),
			Label:        row.Label,
			Position:     int(row.Position),
			Result:       row.Result,
		})
	}
	return items
}

// AnonymizeUserReferences rewrites every reference to a deleted user's account
// to the canonical core.DeletedUserID sentinel in ONE transaction (Story 3.4,
// FR-24/AD-8): `inspections.inspector_id` AND `reinstatements.actor_id` both
// flip, so a failed half-write never leaves mixed references. IDEMPOTENT: a
// user with no matching rows (never inspected/reinstated, or already
// anonymized) is a no-op — the UPDATEs affect zero rows without error. The
// sentinel is a fixed well-known uuid, deliberately absent from users, so the
// DisplayNameResolver seam renders "Deleted User" (the inspection
// history/status report stay fully intact, FR-18). A malformed user id maps to
// core.ErrToolNotFound.
func (r *Repository) AnonymizeUserReferences(ctx context.Context, userID string) error {
	uid, err := parseOptionalUUID(userID)
	if err != nil {
		return core.ErrToolNotFound
	}
	deleted, err := parseOptionalUUID(core.DeletedUserID)
	if err != nil {
		return err
	}

	tx, err := r.beginTx(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after Commit

	q := r.queries.WithTx(tx)
	if err := q.UpdateInspectionsInspector(ctx, UpdateInspectionsInspectorParams{
		InspectorID:   deleted,
		InspectorID_2: uid,
	}); err != nil {
		return err
	}
	if err := q.UpdateReinstatementsActor(ctx, UpdateReinstatementsActorParams{
		ActorID:   deleted,
		ActorID_2: uid,
	}); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return err
	}
	return nil
}

// Compile-time check: the repository satisfies the core InspectionStore port.
var _ core.InspectionStore = (*Repository)(nil)
