package postgres

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/tools/core"
)

// Inspection store implementation (Story 5.3, FR-12/FR-13/FR-14/AD-4/AD-5):
// the transactional inspection+items insert and the derived-status input read
// over the Tool-owned inspections + inspection_items + reinstatements tables
// (migration 000027). Records are append-only — an inspection is immutable
// once persisted (the history surface, FR-18, reads them; there is no update
// path). The reinstatement WRITE path is Story 5.6; this store only CONSULTS
// the table for the clock anchor.

// InsertInspection persists one inspection AND its snapshot items in ONE
// transaction (the Story 2.5 lesson): the inspection row first, then each item
// (label + position snapshotted by the core from the type's checklist). A
// failed item write rolls the whole inspection back — a half-persisted record
// never exists. The ids are generated by the DB (uuidv7); submitted_at is the
// DB now(). Returns the persisted record with its ordered items re-read so the
// response round-trips exactly what the DB holds.
func (r *Repository) InsertInspection(ctx context.Context, inspection *core.Inspection) (*core.Inspection, error) {
	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after Commit

	q := r.queries.WithTx(tx)

	toolID, err := parseOptionalUUID(inspection.ToolID)
	if err != nil {
		return nil, err
	}
	inspectorID, err := parseOptionalUUID(inspection.InspectorID)
	if err != nil {
		return nil, err
	}
	row, err := q.InsertInspection(ctx, InsertInspectionParams{
		ToolID:        toolID,
		InspectorID:   inspectorID,
		Mode:          inspection.Mode,
		OverallResult: inspection.OverallResult,
		Notes:         inspectionNotesValue(inspection.Notes),
	})
	if err != nil {
		return nil, err
	}

	for _, item := range inspection.Items {
		itemID, err := parseOptionalUUID(item.ItemID)
		if err != nil {
			return nil, err
		}
		if err := q.InsertInspectionItem(ctx, InsertInspectionItemParams{
			InspectionID: row.ID,
			ItemID:       itemID,
			Label:        item.Label,
			Position:     int32(item.Position),
			Result:       item.Result,
		}); err != nil {
			return nil, err
		}
	}

	// Re-read the snapshotted items THROUGH the transaction's queries BEFORE
	// committing: a re-read failure here returns a 500 while the record is not
	// yet committed — it must never surface an error AFTER the commit (an
	// already-committed record would be invisible to a client retry and the
	// response would fail for nothing).
	itemRows, err := q.GetInspectionItems(ctx, row.ID)
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return inspectionFromRow(row, itemRows), nil
}

// GetToolInspectionStatus is the derived-status input read (Story 5.3,
// AD-4/AD-5): the LATEST FAILED inspection's submitted_at (the OOS anchor — a
// PASS inspection does NOT clear it), the LATEST PASSING inspection's
// submitted_at and the LATEST reinstatement's created_at. A tool with no
// records at all maps to a nil-safe status (never-inspected → the derivation
// answers `red`); a malformed tool id answers core.ErrToolNotFound.
func (r *Repository) GetToolInspectionStatus(ctx context.Context, toolID string) (*core.ToolInspectionStatus, error) {
	uid, err := parseOptionalUUID(toolID)
	if err != nil {
		return nil, err
	}

	status := &core.ToolInspectionStatus{}

	latestFail, err := r.queries.GetLatestFailedInspection(ctx, uid)
	switch {
	case err == nil:
		if latestFail.Valid {
			t := latestFail.Time
			status.LatestFailAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
		// Never failed: LatestFailAt stays nil (the derivation handles it).
	default:
		return nil, err
	}

	lastSuccess, err := r.queries.GetLatestPassInspection(ctx, uid)
	switch {
	case err == nil:
		if lastSuccess.Valid {
			t := lastSuccess.Time
			status.LastSuccessAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
	default:
		return nil, err
	}

	lastReinstatement, err := r.queries.GetLatestReinstatement(ctx, uid)
	switch {
	case err == nil:
		if lastReinstatement.Valid {
			t := lastReinstatement.Time
			status.LastReinstatedAt = &t
		}
	case errors.Is(err, pgx.ErrNoRows):
	default:
		return nil, err
	}

	return status, nil
}

// inspectionNotesValue encodes the notes for the nullable text column: an empty
// note (the common case) stores SQL NULL, a non-empty one the text.
func inspectionNotesValue(notes string) pgtype.Text {
	if notes == "" {
		return pgtype.Text{}
	}
	return pgtype.Text{String: notes, Valid: true}
}

// inspectionFromRow maps an sqlc inspection row (+ its ordered snapshot items)
// to the domain value. A NULL notes column reads back as "".
func inspectionFromRow(row Inspection, itemRows []InspectionItem) *core.Inspection {
	return &core.Inspection{
		ID:            row.ID.String(),
		ToolID:        row.ToolID.String(),
		InspectorID:   row.InspectorID.String(),
		Mode:          row.Mode,
		OverallResult: row.OverallResult,
		Notes:         row.Notes.String,
		SubmittedAt:   row.SubmittedAt.Time,
		Items:         inspectionItemsFromRows(itemRows),
	}
}

// inspectionItemsFromRows maps the ordered snapshot rows to the domain items
// (already ordered by position — the SQL ORDER BY guarantees it).
func inspectionItemsFromRows(rows []InspectionItem) []core.InspectionItem {
	if len(rows) == 0 {
		return []core.InspectionItem{}
	}
	items := make([]core.InspectionItem, 0, len(rows))
	for _, row := range rows {
		items = append(items, core.InspectionItem{
			ID:           row.ID.String(),
			InspectionID: row.InspectionID.String(),
			ItemID:       row.ItemID.String(),
			Label:        row.Label,
			Position:     int(row.Position),
			Result:       row.Result,
		})
	}
	return items
}

// Compile-time check: the repository satisfies the core InspectionStore port.
var _ core.InspectionStore = (*Repository)(nil)
