// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inspection struct {
	ID            pgtype.UUID        `json:"id"`
	ToolID        pgtype.UUID        `json:"tool_id"`
	InspectorID   pgtype.UUID        `json:"inspector_id"`
	Mode          string             `json:"mode"`
	OverallResult string             `json:"overall_result"`
	Notes         pgtype.Text        `json:"notes"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
}

type InspectionItem struct {
	ID           pgtype.UUID `json:"id"`
	InspectionID pgtype.UUID `json:"inspection_id"`
	ItemID       pgtype.UUID `json:"item_id"`
	Label        string      `json:"label"`
	Position     int32       `json:"position"`
	Result       string      `json:"result"`
}

type Reinstatement struct {
	ID        pgtype.UUID        `json:"id"`
	ToolID    pgtype.UUID        `json:"tool_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tool struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ToolTypeID      pgtype.UUID        `json:"tool_type_id"`
	ScheduleID      pgtype.UUID        `json:"schedule_id"`
	Attributes      []byte             `json:"attributes"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	InventoryNumber string             `json:"inventory_number"`
}

type ToolType struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	DefaultScheduleID       pgtype.UUID        `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID        `json:"required_qualification_id"`
	InspectionMode          string             `json:"inspection_mode"`
	Attributes              []byte             `json:"attributes"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ToolTypeChecklistItem struct {
	ID         pgtype.UUID        `json:"id"`
	ToolTypeID pgtype.UUID        `json:"tool_type_id"`
	Position   int32              `json:"position"`
	Label      string             `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
