// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ToolType struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	DefaultScheduleID       pgtype.UUID        `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID        `json:"required_qualification_id"`
	InspectionMode          string             `json:"inspection_mode"`
	Attributes              []byte             `json:"attributes"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ToolTypeChecklistItem struct {
	ID         pgtype.UUID        `json:"id"`
	ToolTypeID pgtype.UUID        `json:"tool_type_id"`
	Position   int32              `json:"position"`
	Label      string             `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
