// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTool = `-- name: ArchiveTool :one
WITH archived AS (
    UPDATE tools
    SET archived_at = now(),
        updated_at = now()
    WHERE tools.id = $1 AND tools.archived_at IS NULL
    RETURNING tools.id, tools.name, tools.tool_type_id, tools.schedule_id, tools.inventory_number, tools.attributes, tools.archived_at, tools.created_at, tools.updated_at
)
SELECT a.id, a.name, a.tool_type_id, tt.name AS tool_type_name, a.schedule_id, a.inventory_number, a.attributes, a.archived_at, a.created_at, a.updated_at
FROM archived a
JOIN tool_types tt ON tt.id = a.tool_type_id
`

type ArchiveToolRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ToolTypeID      pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName    string             `json:"tool_type_name"`
	ScheduleID      pgtype.UUID        `json:"schedule_id"`
	InventoryNumber string             `json:"inventory_number"`
	Attributes      []byte             `json:"attributes"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Soft-archive one tool: archived_at = now() (never a hard delete — FK
// history intact, AD-10), returning the row JOINed with its type name. The
// `AND archived_at IS NULL` guard makes archiving an already-archived row
// affect zero rows → ErrToolNotFound (the row is non-existent to the surface).
func (q *Queries) ArchiveTool(ctx context.Context, id pgtype.UUID) (ArchiveToolRow, error) {
	row := q.db.QueryRow(ctx, archiveTool, id)
	var i ArchiveToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.InventoryNumber,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveToolType = `-- name: ArchiveToolType :one
UPDATE tool_types
SET archived_at = now(),
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

// Soft-archive one tool type: archived_at = now() (never a hard delete — FK
// history intact, AD-10). The `AND archived_at IS NULL` guard makes archiving
// an already-archived row affect zero rows → ErrToolTypeNotFound (the row is
// non-existent to the surface).
func (q *Queries) ArchiveToolType(ctx context.Context, id pgtype.UUID) (ToolType, error) {
	row := q.db.QueryRow(ctx, archiveToolType, id)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTool = `-- name: CreateTool :one
WITH new_tool AS (
    INSERT INTO tools (name, tool_type_id, schedule_id, inventory_number, attributes)
    VALUES ($1, $2, $3, $5 || lpad(nextval('tools_inventory_number_seq')::text, $6, '0'), $4)
    RETURNING id, name, tool_type_id, schedule_id, inventory_number, attributes, archived_at, created_at, updated_at
)
SELECT nt.id, nt.name, nt.tool_type_id, tt.name AS tool_type_name, nt.schedule_id, nt.inventory_number, nt.attributes, nt.archived_at, nt.created_at, nt.updated_at
FROM new_tool nt
JOIN tool_types tt ON tt.id = nt.tool_type_id
`

type CreateToolParams struct {
	Name            string      `json:"name"`
	ToolTypeID      pgtype.UUID `json:"tool_type_id"`
	ScheduleID      pgtype.UUID `json:"schedule_id"`
	Attributes      []byte      `json:"attributes"`
	InventoryPrefix pgtype.Text `json:"inventory_prefix"`
	InventoryWidth  int32       `json:"inventory_width"`
}

type CreateToolRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ToolTypeID      pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName    string             `json:"tool_type_name"`
	ScheduleID      pgtype.UUID        `json:"schedule_id"`
	InventoryNumber string             `json:"inventory_number"`
	Attributes      []byte             `json:"attributes"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Insert a tool and return the resulting row JOINed with its type name. The
// inventory number is AUTO-ASSIGNED in-SQL (Story 5-2c, C2 adoption): the
// core resolves `inventory_prefix`/`inventory_width` from the Admin
// AppSettingsPort (default 'GEAR' + 9 zero-padded digits) and passes them as
// $5/$6 — the number is `<prefix> || lpad(nextval, <width>, '0')`, atomic,
// monotonic, one round-trip, no client input (CREATE_IGNORE_CLIENT). NOTE:
// once the sequence exceeds 10^width-1 the number NATURALLY widens to
// width+1 digits (e.g. 'GEAR1000000000') — still well inside the CHECK
// (char_length <= 16), monotonic, and fine for the surface. A manual edit can
// consume a future sequence value; a UNIQUE collision on
// tools_inventory_number_key (a case-insensitive functional index) is handled
// by the repository's bounded retry loop (re-running this INSERT computes a
// FRESH nextval). The core validated the type EXISTS + ACTIVE and the
// (optional) schedule override against the SchedulesPort first; an EMPTY
// schedule_id is passed as NULL (inherit the type default, AD-5). A name
// already held by ANY row (active or archived) trips the UNIQUE constraint and
// is mapped by the repository to the German duplicate-name 400.
func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (CreateToolRow, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.Name,
		arg.ToolTypeID,
		arg.ScheduleID,
		arg.Attributes,
		arg.InventoryPrefix,
		arg.InventoryWidth,
	)
	var i CreateToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.InventoryNumber,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolType = `-- name: CreateToolType :one
INSERT INTO tool_types (name, default_schedule_id, required_qualification_id, inspection_mode, attributes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type CreateToolTypeParams struct {
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
	Attributes              []byte      `json:"attributes"`
}

// Insert a tool type and return the resulting row. The attributes jsonb column
// is written explicitly (Story 4.4, FR-10/AD-3): the core passes '{}' for an
// absent field and a validated object otherwise. A name already held by ANY row
// (active or archived) trips the UNIQUE constraint and is mapped by the
// repository to the German duplicate-name 400.
func (q *Queries) CreateToolType(ctx context.Context, arg CreateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, createToolType,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
		arg.Attributes,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteToolTypeChecklistItems = `-- name: DeleteToolTypeChecklistItems :exec
DELETE FROM tool_type_checklist_items WHERE tool_type_id = $1
`

// Remove EVERY checklist item of a tool type (FR-23). Used by the update item
// REPLACEMENT before InsertToolTypeChecklistItem, both in ONE transaction
// (delete-then-insert, separate statements — Story 2.5 lesson).
func (q *Queries) DeleteToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteToolTypeChecklistItems, toolTypeID)
	return err
}

const findToolCollisions = `-- name: FindToolCollisions :many
SELECT name, lower(inventory_number) AS inventory_number
FROM tools
WHERE name = ANY($1::text[]) OR lower(inventory_number) = ANY($2::text[])
`

type FindToolCollisionsParams struct {
	Names            []string `json:"names"`
	InventoryNumbers []string `json:"inventory_numbers"`
}

type FindToolCollisionsRow struct {
	Name            string `json:"name"`
	InventoryNumber string `json:"inventory_number"`
}

// The Story 4.5 collision pre-check (the 4-3b backstop): the input names /
// inventory numbers that are ALREADY held by ANY tools row — ACTIVE AND
// ARCHIVED (an archived tool keeps its name/inventory "taken", so an import
// row whose name/number an archived tool holds fails with a precise German row
// error before the batch). Names match EXACTLY (the DB UNIQUE(name) is
// case-sensitive); inventory matches CASE-INSENSITIVELY via the lower()
// functional index — the caller passes the lowercased input inventories. The
// repository filters the returned rows against the exact input sets so a
// row matched on the OTHER column is never misreported as a hit.
func (q *Queries) FindToolCollisions(ctx context.Context, arg FindToolCollisionsParams) ([]FindToolCollisionsRow, error) {
	rows, err := q.db.Query(ctx, findToolCollisions, arg.Names, arg.InventoryNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindToolCollisionsRow
	for rows.Next() {
		var i FindToolCollisionsRow
		if err := rows.Scan(&i.Name, &i.InventoryNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInspectionItems = `-- name: GetInspectionItems :many
SELECT id, inspection_id, item_id, label, position, result
FROM inspection_items
WHERE inspection_id = $1
ORDER BY position ASC
`

// The snapshotted ordered checklist items of ONE inspection (the item snapshot
// at submit, FR-12), by position.
func (q *Queries) GetInspectionItems(ctx context.Context, inspectionID pgtype.UUID) ([]InspectionItem, error) {
	rows, err := q.db.Query(ctx, getInspectionItems, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionItem
	for rows.Next() {
		var i InspectionItem
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.ItemID,
			&i.Label,
			&i.Position,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestFailedInspection = `-- name: GetLatestFailedInspection :one
SELECT submitted_at
FROM inspections
WHERE tool_id = $1 AND overall_result = 'fail'
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

// The submitted_at of the LATEST FAILED inspection of a tool (the OOS anchor,
// AD-4: OOS is derived from the latest FAILED inspection not since reinstated —
// a PASS inspection does NOT clear it). No row → pgx.ErrNoRows (the repository
// maps it to a nil anchor).
func (q *Queries) GetLatestFailedInspection(ctx context.Context, toolID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestFailedInspection, toolID)
	var submitted_at pgtype.Timestamptz
	err := row.Scan(&submitted_at)
	return submitted_at, err
}

const getLatestInspectionByTool = `-- name: GetLatestInspectionByTool :one
SELECT submitted_at, inspector_id
FROM inspections
WHERE tool_id = $1
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

type GetLatestInspectionByToolRow struct {
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	InspectorID pgtype.UUID        `json:"inspector_id"`
}

// The LATEST inspection of a tool (ANY result — Story 6.2, FR-17): the status
// report's "Zuletzt geprüft" + "Prüfer/in" inputs. The submitted_at DESC,
// id DESC tiebreak is deterministic (the existing 000027 index
// inspections_tool_id_submitted_at_idx already supports it). No row →
// pgx.ErrNoRows (the repository maps it to a nil latest, and the report renders
// "–").
func (q *Queries) GetLatestInspectionByTool(ctx context.Context, toolID pgtype.UUID) (GetLatestInspectionByToolRow, error) {
	row := q.db.QueryRow(ctx, getLatestInspectionByTool, toolID)
	var i GetLatestInspectionByToolRow
	err := row.Scan(&i.SubmittedAt, &i.InspectorID)
	return i, err
}

const getLatestPassInspection = `-- name: GetLatestPassInspection :one
SELECT submitted_at
FROM inspections
WHERE tool_id = $1 AND overall_result = 'pass'
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

// The submitted_at of the LATEST PASSING inspection of a tool (the clock's
// "last successful inspection" anchor, AD-5). No row → pgx.ErrNoRows (the
// repository maps it to a nil anchor).
func (q *Queries) GetLatestPassInspection(ctx context.Context, toolID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestPassInspection, toolID)
	var submitted_at pgtype.Timestamptz
	err := row.Scan(&submitted_at)
	return submitted_at, err
}

const getLatestReinstatement = `-- name: GetLatestReinstatement :one
SELECT created_at
FROM reinstatements
WHERE tool_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The created_at of the LATEST reinstatement of a tool (the clock's
// "last reinstated" anchor, AD-5/AD-9; the WRITE path is Story 5.6). No row →
// pgx.ErrNoRows (the repository maps it to a nil anchor).
func (q *Queries) GetLatestReinstatement(ctx context.Context, toolID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestReinstatement, toolID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getToolTypeChecklistItems = `-- name: GetToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = $1
ORDER BY position ASC
`

// The ordered checklist items of ONE tool type, by position (FR-23).
func (q *Queries) GetToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, getToolTypeChecklistItems, toolTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolWithTypeQualification = `-- name: GetToolWithTypeQualification :one
SELECT t.id, t.name, t.tool_type_id, tt.name AS tool_type_name, tt.required_qualification_id, tt.inspection_mode, t.schedule_id, tt.default_schedule_id
FROM tools t
JOIN tool_types tt ON tt.id = t.tool_type_id
WHERE t.id = $1 AND t.archived_at IS NULL AND tt.archived_at IS NULL
`

type GetToolWithTypeQualificationRow struct {
	ID                      pgtype.UUID `json:"id"`
	Name                    string      `json:"name"`
	ToolTypeID              pgtype.UUID `json:"tool_type_id"`
	ToolTypeName            string      `json:"tool_type_name"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
	ScheduleID              pgtype.UUID `json:"schedule_id"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
}

// The lean inspection-start read (Story 5.1, FR-11/AD-7): the ACTIVE tool plus
// its type's required_qualification_id and inspection_mode (intra-module JOIN on
// Tool-owned tool_types — the Tool module never joins another module's tables,
// AD-8/AD-11). BOTH guards (`t.archived_at IS NULL` AND `tt.archived_at IS
// NULL`) make a tool with an ARCHIVED type (or an archived/missing tool) answer
// ErrToolNotFound — an active tool must never resolve a retired type's gating
// data for the start (the row is non-existent to the surface). Story 5.3 also
// carries the tool's schedule OVERRIDE and the type's DEFAULT schedule id (the
// AD-5 interval-resolution inputs, resolved through the Admin SchedulesPort).
func (q *Queries) GetToolWithTypeQualification(ctx context.Context, id pgtype.UUID) (GetToolWithTypeQualificationRow, error) {
	row := q.db.QueryRow(ctx, getToolWithTypeQualification, id)
	var i GetToolWithTypeQualificationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.ScheduleID,
		&i.DefaultScheduleID,
	)
	return i, err
}

const insertInspection = `-- name: InsertInspection :one

INSERT INTO inspections (tool_id, inspector_id, mode, overall_result, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tool_id, inspector_id, mode, overall_result, notes, submitted_at
`

type InsertInspectionParams struct {
	ToolID        pgtype.UUID `json:"tool_id"`
	InspectorID   pgtype.UUID `json:"inspector_id"`
	Mode          string      `json:"mode"`
	OverallResult string      `json:"overall_result"`
	Notes         pgtype.Text `json:"notes"`
}

// ============================================================================
// Inspection queries (Story 5.3, FR-12/FR-13/FR-14/AD-4/AD-5): the
// Tool-owned inspections + inspection_items + reinstatements tables. The write
// (InsertInspection + InsertInspectionItem) runs in ONE transaction (inspection
// + its snapshot items); the status read (GetToolInspectionStatus's building
// blocks) feeds the shared derived-status/clock function — OOS is NEVER stored.
// ============================================================================
// Insert one inspection record and return the persisted row. The
// overall_result and mode were validated by the core; inspector_id and notes
// are snapshotted plain values (no FK, AD-8/3.4).
func (q *Queries) InsertInspection(ctx context.Context, arg InsertInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, insertInspection,
		arg.ToolID,
		arg.InspectorID,
		arg.Mode,
		arg.OverallResult,
		arg.Notes,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.InspectorID,
		&i.Mode,
		&i.OverallResult,
		&i.Notes,
		&i.SubmittedAt,
	)
	return i, err
}

const insertInspectionItem = `-- name: InsertInspectionItem :exec
INSERT INTO inspection_items (inspection_id, item_id, label, position, result)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInspectionItemParams struct {
	InspectionID pgtype.UUID `json:"inspection_id"`
	ItemID       pgtype.UUID `json:"item_id"`
	Label        string      `json:"label"`
	Position     int32       `json:"position"`
	Result       string      `json:"result"`
}

// Insert one snapshotted checklist item of an inspection (FR-12/FR-23): the
// label + position come from the tool type's checklist at submit time (history
// stays self-contained even if the template later changes); item_id is a plain
// uuid (no FK). Called once per item inside the submit transaction.
func (q *Queries) InsertInspectionItem(ctx context.Context, arg InsertInspectionItemParams) error {
	_, err := q.db.Exec(ctx, insertInspectionItem,
		arg.InspectionID,
		arg.ItemID,
		arg.Label,
		arg.Position,
		arg.Result,
	)
	return err
}

const insertReinstatement = `-- name: InsertReinstatement :one
INSERT INTO reinstatements (tool_id, actor_id, reason)
VALUES ($1, $2, $3)
RETURNING id, tool_id, actor_id, reason, created_at
`

type InsertReinstatementParams struct {
	ToolID  pgtype.UUID `json:"tool_id"`
	ActorID pgtype.UUID `json:"actor_id"`
	Reason  string      `json:"reason"`
}

// Persist one reinstatement (Story 5.6, FR-15/AD-9): tool, actor and the
// MANDATORY reason, created_at = DB now(). The reason was validated by the
// core (non-empty, ≤ 2000 runes); actor_id is a plain uuid (no FK, AD-8/3.4).
// The row immediately flips the derived status — a fail before the latest
// reinstatement is not OOS (AD-4).
func (q *Queries) InsertReinstatement(ctx context.Context, arg InsertReinstatementParams) (Reinstatement, error) {
	row := q.db.QueryRow(ctx, insertReinstatement, arg.ToolID, arg.ActorID, arg.Reason)
	var i Reinstatement
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertToolTypeChecklistItem = `-- name: InsertToolTypeChecklistItem :exec
INSERT INTO tool_type_checklist_items (tool_type_id, position, label)
VALUES ($1, $2, $3)
`

type InsertToolTypeChecklistItemParams struct {
	ToolTypeID pgtype.UUID `json:"tool_type_id"`
	Position   int32       `json:"position"`
	Label      string      `json:"label"`
}

// Insert one ordered checklist item of a tool type (FR-23). Called once per
// item inside the create/update transaction; position comes from the array
// order the client submitted.
func (q *Queries) InsertToolTypeChecklistItem(ctx context.Context, arg InsertToolTypeChecklistItemParams) error {
	_, err := q.db.Exec(ctx, insertToolTypeChecklistItem, arg.ToolTypeID, arg.Position, arg.Label)
	return err
}

const listInspectionItemsByInspector = `-- name: ListInspectionItemsByInspector :many
SELECT ii.id, ii.inspection_id, ii.item_id, ii.label, ii.position, ii.result
FROM inspection_items ii
JOIN inspections i ON i.id = ii.inspection_id
WHERE i.inspector_id = $1
ORDER BY ii.inspection_id, ii.position
`

// The snapshotted ordered checklist items of EVERY inspection the user
// performed (Story 3.3), grouped by inspection and ordered by position within
// each group — the per-inspection item results of the DSGVO export in ONE
// round-trip (no N+1 per-inspection item reads, mirroring the history surface).
func (q *Queries) ListInspectionItemsByInspector(ctx context.Context, inspectorID pgtype.UUID) ([]InspectionItem, error) {
	rows, err := q.db.Query(ctx, listInspectionItemsByInspector, inspectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionItem
	for rows.Next() {
		var i InspectionItem
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.ItemID,
			&i.Label,
			&i.Position,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionItemsByTool = `-- name: ListInspectionItemsByTool :many
SELECT ii.id, ii.inspection_id, ii.item_id, ii.label, ii.position, ii.result
FROM inspection_items ii
JOIN inspections i ON i.id = ii.inspection_id
WHERE i.tool_id = $1
ORDER BY ii.inspection_id, ii.position
`

// The snapshotted ordered checklist items of EVERY inspection of a tool (FR-18
// per-checklist-item results), grouped by inspection and ordered by position
// within each group. The repository groups them onto the fetched inspections
// in ONE round-trip (no N+1 per-inspection item reads).
func (q *Queries) ListInspectionItemsByTool(ctx context.Context, toolID pgtype.UUID) ([]InspectionItem, error) {
	rows, err := q.db.Query(ctx, listInspectionItemsByTool, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionItem
	for rows.Next() {
		var i InspectionItem
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.ItemID,
			&i.Label,
			&i.Position,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsByInspector = `-- name: ListInspectionsByInspector :many

SELECT id, tool_id, inspector_id, mode, overall_result, notes, submitted_at
FROM inspections
WHERE inspector_id = $1
ORDER BY submitted_at DESC, id DESC
`

// ============================================================================
// DSGVO data-access export queries (Story 3.3, FR-24/AD-8): the per-USER reads
// behind the Tool module's DSGVOInspectionExportPort. They filter on the plain
// FK-less inspector_id / actor_id columns (the 000029 indexes
// inspections_inspector_id_idx / reinstatements_actor_id_idx serve them).
// The export stays inside Tool-owned tables (inspections JOIN tools for the
// display name is intra-module, AD-8/AD-11); no actor names resolve here — the
// report subject is the exporting user.
// ============================================================================
// Every inspection the user performed as inspector (FR-24), newest first with
// the id tiebreak. The repository attaches the snapshotted per-checklist-item
// results in one grouped round-trip. A user with no inspections answers an
// empty set (the report renders the German empty note, never a 404).
func (q *Queries) ListInspectionsByInspector(ctx context.Context, inspectorID pgtype.UUID) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByInspector, inspectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inspection
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.InspectorID,
			&i.Mode,
			&i.OverallResult,
			&i.Notes,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsByTool = `-- name: ListInspectionsByTool :many

SELECT id, tool_id, inspector_id, mode, overall_result, notes, submitted_at
FROM inspections
WHERE tool_id = $1
ORDER BY submitted_at DESC, id DESC
`

// ============================================================================
// History queries (Story 6.3, FR-18/AD-6/AD-8): the per-tool audit trail of
// inspections + reinstatements, newest first. The inspector/actor NAMES never
// resolve here — the Tool module never joins user tables (AD-8/AD-11); the
// plain FK-less ids are read out and the core resolves the display names
// through the User module's DisplayNameResolver seam in ONE bulk call.
// ============================================================================
// The FULL inspection history of a tool (FR-18), reverse-chronological with
// the id tiebreak for equal timestamps (submitted_at DESC, id DESC — the same
// deterministic tiebreak as the status-read queries; the existing 000027 index
// inspections_tool_id_submitted_at_idx already supports it). A tool with no
// inspections answers an empty set (the history surface renders the German
// empty state, never a 404).
func (q *Queries) ListInspectionsByTool(ctx context.Context, toolID pgtype.UUID) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByTool, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inspection
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.InspectorID,
			&i.Mode,
			&i.OverallResult,
			&i.Notes,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReinstatementsByActor = `-- name: ListReinstatementsByActor :many
SELECT id, tool_id, actor_id, reason, created_at
FROM reinstatements
WHERE actor_id = $1
ORDER BY created_at DESC, id DESC
`

// Every reinstatement the user performed as actor (FR-24), newest first with
// the id tiebreak. A user with no reinstatements answers an empty set.
func (q *Queries) ListReinstatementsByActor(ctx context.Context, actorID pgtype.UUID) ([]Reinstatement, error) {
	rows, err := q.db.Query(ctx, listReinstatementsByActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reinstatement
	for rows.Next() {
		var i Reinstatement
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.ActorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReinstatementsByTool = `-- name: ListReinstatementsByTool :many
SELECT id, tool_id, actor_id, reason, created_at
FROM reinstatements
WHERE tool_id = $1
ORDER BY created_at DESC, id DESC
`

// The FULL reinstatement ledger of a tool (FR-18), newest first with the id
// tiebreak (created_at DESC, id DESC — the existing 000027 index
// reinstatements_tool_id_created_at_idx already supports it). A tool with no
// reinstatements answers an empty set.
func (q *Queries) ListReinstatementsByTool(ctx context.Context, toolID pgtype.UUID) ([]Reinstatement, error) {
	rows, err := q.db.Query(ctx, listReinstatementsByTool, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reinstatement
	for rows.Next() {
		var i Reinstatement
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.ActorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolNamesByIDs = `-- name: ListToolNamesByIDs :many
SELECT id, name
FROM tools
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListToolNamesByIDsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// The id → name map of the EXISTING tools among the given set (Story 3.3): the
// DSGVO export resolves the display names of the tools the subject inspected /
// reinstated, INCLUDING archived ones (the report covers the full fleet
// history, so the active-only ListTools would drop archived rows). The read is
// intra-module (Tool-owned tools, AD-8/AD-11). A tool id ABSENT from the
// result (concurrent deletion) is simply a MISSING key — the export falls back
// to the id itself, never a 404.
func (q *Queries) ListToolNamesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListToolNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listToolNamesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToolNamesByIDsRow
	for rows.Next() {
		var i ListToolNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolTypeChecklistItems = `-- name: ListToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = ANY($1::uuid[])
ORDER BY tool_type_id ASC, position ASC
`

// The ordered checklist items of a SET of tool types (FR-23), grouped by
// tool_type_id and ordered by position within each group. The repository groups
// them onto the fetched tool types in one round-trip for the GET_LIST surface.
func (q *Queries) ListToolTypeChecklistItems(ctx context.Context, dollar_1 []pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, listToolTypeChecklistItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolTypes = `-- name: ListToolTypes :many

SELECT id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
FROM tool_types
WHERE archived_at IS NULL
ORDER BY created_at ASC, name ASC
`

// Tool module store (AD-1/AD-10/AD-11), generated into package postgres by
// sqlc. Story 4.2 ships the tool-type catalog queries over the Tool-owned
// `tool_types` + `tool_type_checklist_items` tables (FR-8/FR-10/FR-23). The
// schema input is the single migration 000021 (see sqlc.yaml); the Tool module
// never joins another module's tables — the cross-module FKs are validated
// through the modules' read-only ports at the core layer.
// The ACTIVE tool-type catalog (FR-8/AD-10). Archived rows (archived_at NOT
// NULL) are filtered out — the active surface never shows them. The order is
// deterministic: created_at ASC with a name tiebreaker.
func (q *Queries) ListToolTypes(ctx context.Context) ([]ToolType, error) {
	rows, err := q.db.Query(ctx, listToolTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolType
	for rows.Next() {
		var i ToolType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultScheduleID,
			&i.RequiredQualificationID,
			&i.InspectionMode,
			&i.Attributes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many

SELECT t.id, t.name, t.tool_type_id, tt.name AS tool_type_name, t.schedule_id, tt.default_schedule_id AS default_schedule_id, t.inventory_number, t.attributes, t.archived_at, t.created_at, t.updated_at
FROM tools t
JOIN tool_types tt ON tt.id = t.tool_type_id
WHERE t.archived_at IS NULL
ORDER BY t.created_at ASC, t.name ASC
`

type ListToolsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	ToolTypeID        pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName      string             `json:"tool_type_name"`
	ScheduleID        pgtype.UUID        `json:"schedule_id"`
	DefaultScheduleID pgtype.UUID        `json:"default_schedule_id"`
	InventoryNumber   string             `json:"inventory_number"`
	Attributes        []byte             `json:"attributes"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// Tool queries (Story 4.3, FR-9/FR-10/AD-5/AD-10): the physical tools that
// belong to a tool type. Every read/write joins the Tool-OWNED `tool_types`
// for the type display name (AD-8/AD-11: the Tool module only joins ITS OWN
// tables — the cross-module schedules override is validated through the Admin
// SchedulesPort, never by joining the Admin tables).
// ============================================================================
// The ACTIVE tool catalog (FR-9/AD-10), each with its tool type's display name
// (JOIN on Tool-owned tool_types). Archived rows (archived_at NOT NULL) are
// filtered out — the active surface never shows them. The order is
// deterministic: created_at ASC with a name tiebreaker. An empty schedule_id
// (SQL NULL) means the tool inherits its type's default schedule (AD-5); the
// type's default_schedule_id is carried alongside (Story 6.1: the dashboard's
// interval-resolution input, via the Tool-owned JOIN — never a cross-module
// join, AD-8/AD-11).
func (q *Queries) ListTools(ctx context.Context) ([]ListToolsRow, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToolsRow
	for rows.Next() {
		var i ListToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ToolTypeID,
			&i.ToolTypeName,
			&i.ScheduleID,
			&i.DefaultScheduleID,
			&i.InventoryNumber,
			&i.Attributes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolExistsActive = `-- name: ToolExistsActive :one
SELECT EXISTS (
    SELECT 1 FROM tools
    WHERE id = $1 AND archived_at IS NULL
)
`

// A lean existence check used by the update path to resolve the archived
// sentinel BEFORE the duplicate-name guard (so updating an unknown/archived id
// never answers a duplicate-name 400). Reports whether the row exists AND is
// still active (archived_at IS NULL); the store maps a false result to
// ErrToolNotFound.
func (q *Queries) ToolExistsActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toolExistsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const toolTypeExistsActive = `-- name: ToolTypeExistsActive :one
SELECT EXISTS (
    SELECT 1 FROM tool_types
    WHERE id = $1 AND archived_at IS NULL
)
`

// A lean existence check used by the update path to resolve the archived
// sentinel BEFORE the duplicate-name guard (so updating an unknown/archived id
// never answers a duplicate-name 400). Reports whether the row exists AND is
// still active (archived_at IS NULL); the store maps a false result to
// ErrToolTypeNotFound. No checklist items are fetched (they are not used here).
func (q *Queries) ToolTypeExistsActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toolTypeExistsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateInspectionsInspector = `-- name: UpdateInspectionsInspector :exec

UPDATE inspections
SET inspector_id = $1
WHERE inspector_id = $2
`

type UpdateInspectionsInspectorParams struct {
	InspectorID   pgtype.UUID `json:"inspector_id"`
	InspectorID_2 pgtype.UUID `json:"inspector_id_2"`
}

// ============================================================================
// DSGVO account-deletion anonymization queries (Story 3.4, FR-24/AD-8): the
// per-reference rewrites behind the Tool module's DSGVODeletionPort. The
// plain FK-less inspector_id / actor_id columns (000027) flip to the canonical
// DeletedUserID sentinel; the repository runs BOTH in ONE transaction. Both
// are idempotent by construction (no matching rows → a no-op).
// ============================================================================
// Rewrite every inspection the erased user performed as inspector to the
// canonical DeletedUserID sentinel. Zero rows when the user never inspected
// (no-op, never an error).
func (q *Queries) UpdateInspectionsInspector(ctx context.Context, arg UpdateInspectionsInspectorParams) error {
	_, err := q.db.Exec(ctx, updateInspectionsInspector, arg.InspectorID, arg.InspectorID_2)
	return err
}

const updateReinstatementsActor = `-- name: UpdateReinstatementsActor :exec
UPDATE reinstatements
SET actor_id = $1
WHERE actor_id = $2
`

type UpdateReinstatementsActorParams struct {
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorID_2 pgtype.UUID `json:"actor_id_2"`
}

// Rewrite every reinstatement the erased user performed as actor to the
// canonical DeletedUserID sentinel. Zero rows when the user never reinstated
// (no-op, never an error).
func (q *Queries) UpdateReinstatementsActor(ctx context.Context, arg UpdateReinstatementsActorParams) error {
	_, err := q.db.Exec(ctx, updateReinstatementsActor, arg.ActorID, arg.ActorID_2)
	return err
}

const updateTool = `-- name: UpdateTool :one
WITH updated AS (
    UPDATE tools
    SET name = $2,
        tool_type_id = $3,
        schedule_id = $4,
        inventory_number = $5,
        attributes = COALESCE($6, attributes),
        updated_at = now()
    WHERE tools.id = $1 AND tools.archived_at IS NULL
    RETURNING tools.id, tools.name, tools.tool_type_id, tools.schedule_id, tools.inventory_number, tools.attributes, tools.archived_at, tools.created_at, tools.updated_at
)
SELECT u.id, u.name, u.tool_type_id, tt.name AS tool_type_name, u.schedule_id, u.inventory_number, u.attributes, u.archived_at, u.created_at, u.updated_at
FROM updated u
JOIN tool_types tt ON tt.id = u.tool_type_id
`

type UpdateToolParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	ToolTypeID      pgtype.UUID `json:"tool_type_id"`
	ScheduleID      pgtype.UUID `json:"schedule_id"`
	InventoryNumber string      `json:"inventory_number"`
	Attributes      []byte      `json:"attributes"`
}

type UpdateToolRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ToolTypeID      pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName    string             `json:"tool_type_name"`
	ScheduleID      pgtype.UUID        `json:"schedule_id"`
	InventoryNumber string             `json:"inventory_number"`
	Attributes      []byte             `json:"attributes"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Replace one ACTIVE tool's core fields and refresh updated_at, returning the
// row JOINed with its type name. The `AND archived_at IS NULL` guard makes an
// update against an already-archived row affect zero rows → ErrToolNotFound
// (soft archive is irreversible in V1; the archived row is non-existent to the
// surface). The schedule override REPLACES the stored value, so clearing it
// (schedule_id NULL) makes the tool inherit its type's default again
// (UPDATE_CLEAR_OVERRIDE, AD-5). The inventory number REPLACES the stored value
// too (Story 4-3b, UPDATE_INVENTORY): the core already validated it non-empty
// + bounded + unique case-insensitively among active tools; a reuse of a number
// held by ANOTHER row (active or archived — incl. case-variants, via the
// lower() functional UNIQUE index) is mapped by the repository to the German
// duplicate-inventory 400. The attributes jsonb column follows the shared
// contract (Story 4.4): COALESCE($6, attributes) keeps the stored value when
// the core passes a NIL map ("absent = unchanged"), while an explicit '{}' (a
// non-NIL value) clears it and a non-empty object replaces it.
func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (UpdateToolRow, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.ID,
		arg.Name,
		arg.ToolTypeID,
		arg.ScheduleID,
		arg.InventoryNumber,
		arg.Attributes,
	)
	var i UpdateToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.InventoryNumber,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolType = `-- name: UpdateToolType :one
UPDATE tool_types
SET name = $2,
    default_schedule_id = $3,
    required_qualification_id = $4,
    inspection_mode = $5,
    attributes = COALESCE($6, attributes),
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type UpdateToolTypeParams struct {
	ID                      pgtype.UUID `json:"id"`
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
	Attributes              []byte      `json:"attributes"`
}

// Replace one ACTIVE tool type's core fields and refresh updated_at. The
// `AND archived_at IS NULL` guard makes an update against an already-archived
// row affect zero rows → ErrToolTypeNotFound (soft archive is irreversible in
// V1; the archived row is non-existent to the surface). The attributes jsonb
// column follows the shared contract (Story 4.4): COALESCE($6, attributes)
// keeps the stored value when the core passes a NIL map ("absent = unchanged"),
// while an explicit '{}' (a non-NIL value) clears it and a non-empty object
// replaces it.
func (q *Queries) UpdateToolType(ctx context.Context, arg UpdateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, updateToolType,
		arg.ID,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
		arg.Attributes,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
