// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTool = `-- name: ArchiveTool :one
WITH archived AS (
    UPDATE tools
    SET archived_at = now(),
        updated_at = now()
    WHERE tools.id = $1 AND tools.archived_at IS NULL
    RETURNING tools.id, tools.name, tools.tool_type_id, tools.schedule_id, tools.attributes, tools.archived_at, tools.created_at, tools.updated_at
)
SELECT a.id, a.name, a.tool_type_id, tt.name AS tool_type_name, a.schedule_id, a.attributes, a.archived_at, a.created_at, a.updated_at
FROM archived a
JOIN tool_types tt ON tt.id = a.tool_type_id
`

type ArchiveToolRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ToolTypeID   pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName string             `json:"tool_type_name"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	Attributes   []byte             `json:"attributes"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Soft-archive one tool: archived_at = now() (never a hard delete — FK
// history intact, AD-10), returning the row JOINed with its type name. The
// `AND archived_at IS NULL` guard makes archiving an already-archived row
// affect zero rows → ErrToolNotFound (the row is non-existent to the surface).
func (q *Queries) ArchiveTool(ctx context.Context, id pgtype.UUID) (ArchiveToolRow, error) {
	row := q.db.QueryRow(ctx, archiveTool, id)
	var i ArchiveToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveToolType = `-- name: ArchiveToolType :one
UPDATE tool_types
SET archived_at = now(),
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

// Soft-archive one tool type: archived_at = now() (never a hard delete — FK
// history intact, AD-10). The `AND archived_at IS NULL` guard makes archiving
// an already-archived row affect zero rows → ErrToolTypeNotFound (the row is
// non-existent to the surface).
func (q *Queries) ArchiveToolType(ctx context.Context, id pgtype.UUID) (ToolType, error) {
	row := q.db.QueryRow(ctx, archiveToolType, id)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTool = `-- name: CreateTool :one
WITH new_tool AS (
    INSERT INTO tools (name, tool_type_id, schedule_id, attributes)
    VALUES ($1, $2, $3, $4)
    RETURNING id, name, tool_type_id, schedule_id, attributes, archived_at, created_at, updated_at
)
SELECT nt.id, nt.name, nt.tool_type_id, tt.name AS tool_type_name, nt.schedule_id, nt.attributes, nt.archived_at, nt.created_at, nt.updated_at
FROM new_tool nt
JOIN tool_types tt ON tt.id = nt.tool_type_id
`

type CreateToolParams struct {
	Name       string      `json:"name"`
	ToolTypeID pgtype.UUID `json:"tool_type_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
	Attributes []byte      `json:"attributes"`
}

type CreateToolRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ToolTypeID   pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName string             `json:"tool_type_name"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	Attributes   []byte             `json:"attributes"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Insert a tool and return the resulting row JOINed with its type name. The
// core validated the type EXISTS + ACTIVE and the (optional) schedule override
// against the SchedulesPort first; an EMPTY schedule_id is passed as NULL
// (inherit the type default, AD-5). A name already held by ANY row (active or
// archived) trips the UNIQUE constraint and is mapped by the repository to the
// German duplicate-name 400.
func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (CreateToolRow, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.Name,
		arg.ToolTypeID,
		arg.ScheduleID,
		arg.Attributes,
	)
	var i CreateToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolType = `-- name: CreateToolType :one
INSERT INTO tool_types (name, default_schedule_id, required_qualification_id, inspection_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type CreateToolTypeParams struct {
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
}

// Insert a tool type and return the resulting row. The attributes jsonb column
// is intentionally omitted — the DB default '{}' applies (FR-10/AD-3). A name
// already held by ANY row (active or archived) trips the UNIQUE constraint and
// is mapped by the repository to the German duplicate-name 400.
func (q *Queries) CreateToolType(ctx context.Context, arg CreateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, createToolType,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteToolTypeChecklistItems = `-- name: DeleteToolTypeChecklistItems :exec
DELETE FROM tool_type_checklist_items WHERE tool_type_id = $1
`

// Remove EVERY checklist item of a tool type (FR-23). Used by the update item
// REPLACEMENT before InsertToolTypeChecklistItem, both in ONE transaction
// (delete-then-insert, separate statements — Story 2.5 lesson).
func (q *Queries) DeleteToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteToolTypeChecklistItems, toolTypeID)
	return err
}

const getToolTypeChecklistItems = `-- name: GetToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = $1
ORDER BY position ASC
`

// The ordered checklist items of ONE tool type, by position (FR-23).
func (q *Queries) GetToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, getToolTypeChecklistItems, toolTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToolTypeChecklistItem = `-- name: InsertToolTypeChecklistItem :exec
INSERT INTO tool_type_checklist_items (tool_type_id, position, label)
VALUES ($1, $2, $3)
`

type InsertToolTypeChecklistItemParams struct {
	ToolTypeID pgtype.UUID `json:"tool_type_id"`
	Position   int32       `json:"position"`
	Label      string      `json:"label"`
}

// Insert one ordered checklist item of a tool type (FR-23). Called once per
// item inside the create/update transaction; position comes from the array
// order the client submitted.
func (q *Queries) InsertToolTypeChecklistItem(ctx context.Context, arg InsertToolTypeChecklistItemParams) error {
	_, err := q.db.Exec(ctx, insertToolTypeChecklistItem, arg.ToolTypeID, arg.Position, arg.Label)
	return err
}

const listToolTypeChecklistItems = `-- name: ListToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = ANY($1::uuid[])
ORDER BY tool_type_id ASC, position ASC
`

// The ordered checklist items of a SET of tool types (FR-23), grouped by
// tool_type_id and ordered by position within each group. The repository groups
// them onto the fetched tool types in one round-trip for the GET_LIST surface.
func (q *Queries) ListToolTypeChecklistItems(ctx context.Context, dollar_1 []pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, listToolTypeChecklistItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolTypes = `-- name: ListToolTypes :many

SELECT id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
FROM tool_types
WHERE archived_at IS NULL
ORDER BY created_at ASC, name ASC
`

// Tool module store (AD-1/AD-10/AD-11), generated into package postgres by
// sqlc. Story 4.2 ships the tool-type catalog queries over the Tool-owned
// `tool_types` + `tool_type_checklist_items` tables (FR-8/FR-10/FR-23). The
// schema input is the single migration 000021 (see sqlc.yaml); the Tool module
// never joins another module's tables — the cross-module FKs are validated
// through the modules' read-only ports at the core layer.
// The ACTIVE tool-type catalog (FR-8/AD-10). Archived rows (archived_at NOT
// NULL) are filtered out — the active surface never shows them. The order is
// deterministic: created_at ASC with a name tiebreaker.
func (q *Queries) ListToolTypes(ctx context.Context) ([]ToolType, error) {
	rows, err := q.db.Query(ctx, listToolTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolType
	for rows.Next() {
		var i ToolType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultScheduleID,
			&i.RequiredQualificationID,
			&i.InspectionMode,
			&i.Attributes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many

SELECT t.id, t.name, t.tool_type_id, tt.name AS tool_type_name, t.schedule_id, t.attributes, t.archived_at, t.created_at, t.updated_at
FROM tools t
JOIN tool_types tt ON tt.id = t.tool_type_id
WHERE t.archived_at IS NULL
ORDER BY t.created_at ASC, t.name ASC
`

type ListToolsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ToolTypeID   pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName string             `json:"tool_type_name"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	Attributes   []byte             `json:"attributes"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// Tool queries (Story 4.3, FR-9/FR-10/AD-5/AD-10): the physical tools that
// belong to a tool type. Every read/write joins the Tool-OWNED `tool_types`
// for the type display name (AD-8/AD-11: the Tool module only joins ITS OWN
// tables — the cross-module schedules override is validated through the Admin
// SchedulesPort, never by joining the Admin tables).
// ============================================================================
// The ACTIVE tool catalog (FR-9/AD-10), each with its tool type's display name
// (JOIN on Tool-owned tool_types). Archived rows (archived_at NOT NULL) are
// filtered out — the active surface never shows them. The order is
// deterministic: created_at ASC with a name tiebreaker. An empty schedule_id
// (SQL NULL) means the tool inherits its type's default schedule (AD-5).
func (q *Queries) ListTools(ctx context.Context) ([]ListToolsRow, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToolsRow
	for rows.Next() {
		var i ListToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ToolTypeID,
			&i.ToolTypeName,
			&i.ScheduleID,
			&i.Attributes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolExistsActive = `-- name: ToolExistsActive :one
SELECT EXISTS (
    SELECT 1 FROM tools
    WHERE id = $1 AND archived_at IS NULL
)
`

// A lean existence check used by the update path to resolve the archived
// sentinel BEFORE the duplicate-name guard (so updating an unknown/archived id
// never answers a duplicate-name 400). Reports whether the row exists AND is
// still active (archived_at IS NULL); the store maps a false result to
// ErrToolNotFound.
func (q *Queries) ToolExistsActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toolExistsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const toolTypeExistsActive = `-- name: ToolTypeExistsActive :one
SELECT EXISTS (
    SELECT 1 FROM tool_types
    WHERE id = $1 AND archived_at IS NULL
)
`

// A lean existence check used by the update path to resolve the archived
// sentinel BEFORE the duplicate-name guard (so updating an unknown/archived id
// never answers a duplicate-name 400). Reports whether the row exists AND is
// still active (archived_at IS NULL); the store maps a false result to
// ErrToolTypeNotFound. No checklist items are fetched (they are not used here).
func (q *Queries) ToolTypeExistsActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toolTypeExistsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTool = `-- name: UpdateTool :one
WITH updated AS (
    UPDATE tools
    SET name = $2,
        tool_type_id = $3,
        schedule_id = $4,
        attributes = $5,
        updated_at = now()
    WHERE tools.id = $1 AND tools.archived_at IS NULL
    RETURNING tools.id, tools.name, tools.tool_type_id, tools.schedule_id, tools.attributes, tools.archived_at, tools.created_at, tools.updated_at
)
SELECT u.id, u.name, u.tool_type_id, tt.name AS tool_type_name, u.schedule_id, u.attributes, u.archived_at, u.created_at, u.updated_at
FROM updated u
JOIN tool_types tt ON tt.id = u.tool_type_id
`

type UpdateToolParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	ToolTypeID pgtype.UUID `json:"tool_type_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
	Attributes []byte      `json:"attributes"`
}

type UpdateToolRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ToolTypeID   pgtype.UUID        `json:"tool_type_id"`
	ToolTypeName string             `json:"tool_type_name"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	Attributes   []byte             `json:"attributes"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Replace one ACTIVE tool's core fields and refresh updated_at, returning the
// row JOINed with its type name. The `AND archived_at IS NULL` guard makes an
// update against an already-archived row affect zero rows → ErrToolNotFound
// (soft archive is irreversible in V1; the archived row is non-existent to the
// surface). The schedule override REPLACES the stored value, so clearing it
// (schedule_id NULL) makes the tool inherit its type's default again
// (UPDATE_CLEAR_OVERRIDE, AD-5).
func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (UpdateToolRow, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.ID,
		arg.Name,
		arg.ToolTypeID,
		arg.ScheduleID,
		arg.Attributes,
	)
	var i UpdateToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToolTypeID,
		&i.ToolTypeName,
		&i.ScheduleID,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolType = `-- name: UpdateToolType :one
UPDATE tool_types
SET name = $2,
    default_schedule_id = $3,
    required_qualification_id = $4,
    inspection_mode = $5,
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type UpdateToolTypeParams struct {
	ID                      pgtype.UUID `json:"id"`
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
}

// Replace one ACTIVE tool type's core fields and refresh updated_at. The
// `AND archived_at IS NULL` guard makes an update against an already-archived
// row affect zero rows → ErrToolTypeNotFound (soft archive is irreversible in
// V1; the archived row is non-existent to the surface). The attributes jsonb
// column is left untouched (Story 4.4 owns its surface).
func (q *Queries) UpdateToolType(ctx context.Context, arg UpdateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, updateToolType,
		arg.ID,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
