// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveToolType = `-- name: ArchiveToolType :one
UPDATE tool_types
SET archived_at = now(),
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

// Soft-archive one tool type: archived_at = now() (never a hard delete — FK
// history intact, AD-10). The `AND archived_at IS NULL` guard makes archiving
// an already-archived row affect zero rows → ErrToolTypeNotFound (the row is
// non-existent to the surface).
func (q *Queries) ArchiveToolType(ctx context.Context, id pgtype.UUID) (ToolType, error) {
	row := q.db.QueryRow(ctx, archiveToolType, id)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolType = `-- name: CreateToolType :one
INSERT INTO tool_types (name, default_schedule_id, required_qualification_id, inspection_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type CreateToolTypeParams struct {
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
}

// Insert a tool type and return the resulting row. The attributes jsonb column
// is intentionally omitted — the DB default '{}' applies (FR-10/AD-3). A name
// already held by ANY row (active or archived) trips the UNIQUE constraint and
// is mapped by the repository to the German duplicate-name 400.
func (q *Queries) CreateToolType(ctx context.Context, arg CreateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, createToolType,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteToolTypeChecklistItems = `-- name: DeleteToolTypeChecklistItems :exec
DELETE FROM tool_type_checklist_items WHERE tool_type_id = $1
`

// Remove EVERY checklist item of a tool type (FR-23). Used by the update item
// REPLACEMENT before InsertToolTypeChecklistItem, both in ONE transaction
// (delete-then-insert, separate statements — Story 2.5 lesson).
func (q *Queries) DeleteToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteToolTypeChecklistItems, toolTypeID)
	return err
}

const getToolTypeChecklistItems = `-- name: GetToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = $1
ORDER BY position ASC
`

// The ordered checklist items of ONE tool type, by position (FR-23).
func (q *Queries) GetToolTypeChecklistItems(ctx context.Context, toolTypeID pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, getToolTypeChecklistItems, toolTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToolTypeChecklistItem = `-- name: InsertToolTypeChecklistItem :exec
INSERT INTO tool_type_checklist_items (tool_type_id, position, label)
VALUES ($1, $2, $3)
`

type InsertToolTypeChecklistItemParams struct {
	ToolTypeID pgtype.UUID `json:"tool_type_id"`
	Position   int32       `json:"position"`
	Label      string      `json:"label"`
}

// Insert one ordered checklist item of a tool type (FR-23). Called once per
// item inside the create/update transaction; position comes from the array
// order the client submitted.
func (q *Queries) InsertToolTypeChecklistItem(ctx context.Context, arg InsertToolTypeChecklistItemParams) error {
	_, err := q.db.Exec(ctx, insertToolTypeChecklistItem, arg.ToolTypeID, arg.Position, arg.Label)
	return err
}

const listToolTypeChecklistItems = `-- name: ListToolTypeChecklistItems :many
SELECT id, tool_type_id, position, label, created_at, updated_at
FROM tool_type_checklist_items
WHERE tool_type_id = ANY($1::uuid[])
ORDER BY tool_type_id ASC, position ASC
`

// The ordered checklist items of a SET of tool types (FR-23), grouped by
// tool_type_id and ordered by position within each group. The repository groups
// them onto the fetched tool types in one round-trip for the GET_LIST surface.
func (q *Queries) ListToolTypeChecklistItems(ctx context.Context, dollar_1 []pgtype.UUID) ([]ToolTypeChecklistItem, error) {
	rows, err := q.db.Query(ctx, listToolTypeChecklistItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolTypeChecklistItem
	for rows.Next() {
		var i ToolTypeChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolTypeID,
			&i.Position,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolTypes = `-- name: ListToolTypes :many

SELECT id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
FROM tool_types
WHERE archived_at IS NULL
ORDER BY created_at ASC, name ASC
`

// Tool module store (AD-1/AD-10/AD-11), generated into package postgres by
// sqlc. Story 4.2 ships the tool-type catalog queries over the Tool-owned
// `tool_types` + `tool_type_checklist_items` tables (FR-8/FR-10/FR-23). The
// schema input is the single migration 000021 (see sqlc.yaml); the Tool module
// never joins another module's tables — the cross-module FKs are validated
// through the modules' read-only ports at the core layer.
// The ACTIVE tool-type catalog (FR-8/AD-10). Archived rows (archived_at NOT
// NULL) are filtered out — the active surface never shows them. The order is
// deterministic: created_at ASC with a name tiebreaker.
func (q *Queries) ListToolTypes(ctx context.Context) ([]ToolType, error) {
	rows, err := q.db.Query(ctx, listToolTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolType
	for rows.Next() {
		var i ToolType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultScheduleID,
			&i.RequiredQualificationID,
			&i.InspectionMode,
			&i.Attributes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolTypeExistsActive = `-- name: ToolTypeExistsActive :one
SELECT EXISTS (
    SELECT 1 FROM tool_types
    WHERE id = $1 AND archived_at IS NULL
)
`

// A lean existence check used by the update path to resolve the archived
// sentinel BEFORE the duplicate-name guard (so updating an unknown/archived id
// never answers a duplicate-name 400). Reports whether the row exists AND is
// still active (archived_at IS NULL); the store maps a false result to
// ErrToolTypeNotFound. No checklist items are fetched (they are not used here).
func (q *Queries) ToolTypeExistsActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toolTypeExistsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateToolType = `-- name: UpdateToolType :one
UPDATE tool_types
SET name = $2,
    default_schedule_id = $3,
    required_qualification_id = $4,
    inspection_mode = $5,
    updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, default_schedule_id, required_qualification_id, inspection_mode, attributes, archived_at, created_at, updated_at
`

type UpdateToolTypeParams struct {
	ID                      pgtype.UUID `json:"id"`
	Name                    string      `json:"name"`
	DefaultScheduleID       pgtype.UUID `json:"default_schedule_id"`
	RequiredQualificationID pgtype.UUID `json:"required_qualification_id"`
	InspectionMode          string      `json:"inspection_mode"`
}

// Replace one ACTIVE tool type's core fields and refresh updated_at. The
// `AND archived_at IS NULL` guard makes an update against an already-archived
// row affect zero rows → ErrToolTypeNotFound (soft archive is irreversible in
// V1; the archived row is non-existent to the surface). The attributes jsonb
// column is left untouched (Story 4.4 owns its surface).
func (q *Queries) UpdateToolType(ctx context.Context, arg UpdateToolTypeParams) (ToolType, error) {
	row := q.db.QueryRow(ctx, updateToolType,
		arg.ID,
		arg.Name,
		arg.DefaultScheduleID,
		arg.RequiredQualificationID,
		arg.InspectionMode,
	)
	var i ToolType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultScheduleID,
		&i.RequiredQualificationID,
		&i.InspectionMode,
		&i.Attributes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
