package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/tools/core"
)

// maxInventoryNumberRetries is the bounded retry budget for the auto-assigned
// inventory number (Story 4-3b): when the INSERT computes a nextval that a
// MANUAL edit already consumed (a future sequence value), the UNIQUE index
// trips and the repository re-runs the INSERT — which computes a FRESH nextval
// in-SQL. After this many consecutive collisions the create fails with the
// German collision 400.
const maxInventoryNumberRetries = 3

// Tool store implementation (Story 4.3, FR-9/FR-10/AD-5/AD-10): list-active
// (each tool JOINed with its Tool-owned type name) / create / update (with
// override-clear → NULL) / archive over the Tool-owned `tools` table. Soft
// archive only — no hard delete (FK history preserved). The `archived_at IS
// NULL` guard on update/archive makes an already-archived row non-existent to
// the surface (ErrToolNotFound). The tool's type FK is intra-module (Tool-owned
// tool_types); the optional schedule override is a first-class FK to the
// Admin-owned schedules catalog (validated at the core against the
// SchedulesPort) — an empty override is stored as SQL NULL (inherit the type
// default, AD-5), mirroring the optional-qualification precedent (parseToolTypeID
// empty → pgtype.UUID{} → NULL).

// ListToolNamesByIDs resolves the id → display name map of the EXISTING tools
// among the given set (Story 3.3 DSGVO export, FR-24/AD-8): the report names
// the tools the subject inspected / reinstated — INCLUDING archived ones (the
// export covers the full fleet history, so the active-only ListTools would
// drop archived rows). Intra-module read over Tool-owned tools (AD-8/AD-11). A
// tool id ABSENT from the result (a concurrent deletion) is simply a MISSING
// key — the core falls back to the id itself, never a 404. An empty input
// answers an empty map (no query).
func (r *Repository) ListToolNamesByIDs(ctx context.Context, toolIDs []string) (map[string]string, error) {
	if len(toolIDs) == 0 {
		return map[string]string{}, nil
	}
	uuids, err := uuidSlice(toolIDs)
	if err != nil {
		return nil, err
	}
	rows, err := r.queries.ListToolNamesByIDs(ctx, uuids)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(rows))
	for _, row := range rows {
		out[row.ID.String()] = row.Name
	}
	return out, nil
}

// CreateTool inserts one tool (CREATE_VALID / CREATE_OVERRIDE / CREATE_AUTO /
// CREATE_IGNORE_CLIENT / CREATE_COLLISION). The id is generated by the DB
// (uuidv7); an EMPTY schedule override is stored as NULL (AD-5). The inventory
// number is AUTO-ASSIGNED in-SQL (`<inventoryPrefix> || zero-padded nextval`
// — Story 5-2c: the core resolved inventory_prefix/inventory_width from the
// Admin AppSettingsPort, atomic, monotonic — the client's inventory is ignored
// on create). When a manual edit consumed the generated sequence value, the
// INSERT trips the tools_inventory_number_key UNIQUE index and the insert is
// RETRIED with a FRESH nextval (bounded to maxInventoryNumberRetries, then the
// German collision 400). Attributes (Story 4.4) are stored in the `attributes`
// JSONB column — the core already defaulted an absent field to the empty map,
// so a nil map never reaches this path. Duplicate-name
// semantics (coherent with the core's active-only case-insensitive guard): an
// EXACT name reuse of an archived row (invisible to the core guard) trips the
// DB UNIQUE constraint and is mapped to the German duplicate-name 400. A DB-level FK
// violation (the tool type or the schedule override vanished between the core
// check and this insert) is mapped to the German 400 — never a raw pg error /
// 500.
func (r *Repository) CreateTool(ctx context.Context, tool *core.Tool, inventoryPrefix string, inventoryWidth int) (*core.Tool, error) {
	toolTypeID, err := parseToolTypeID(tool.ToolTypeID)
	if err != nil {
		return nil, err
	}
	schedule, err := parseOptionalUUID(tool.ScheduleID)
	if err != nil {
		return nil, err
	}
	attrs, err := marshalToolAttributes(tool.Attributes)
	if err != nil {
		return nil, err
	}
	params := CreateToolParams{
		Name:            tool.Name,
		ToolTypeID:      toolTypeID,
		ScheduleID:      schedule,
		Attributes:      attrs,
		InventoryPrefix: pgtype.Text{String: inventoryPrefix, Valid: inventoryPrefix != ""},
		InventoryWidth:  int32(inventoryWidth),
	}
	for attempt := 0; attempt < maxInventoryNumberRetries; attempt++ {
		row, err := r.queries.CreateTool(ctx, params)
		if err == nil {
			return toolFromRow(row), nil
		}
		if isInventoryNumberCollision(err) {
			// The auto-assigned nextval collided with a manually-entered number
			// (a manual edit consumed a future sequence value). The next attempt
			// re-runs the INSERT, which computes a FRESH nextval in-SQL — no new
			// query, no client involvement.
			continue
		}
		if isUniqueViolation(err) {
			return nil, &core.InvalidToolError{Message: core.MsgToolNameTaken}
		}
		if isForeignKeyViolation(err) {
			// A race between the core's FK checks and this insert (the type
			// archived / the schedule override archived meanwhile) surfaces as
			// SQLSTATE 23503 — map it to the German 400, never a raw pg error /
			// 500.
			return nil, &core.InvalidToolError{Message: core.MsgToolReferencedGone}
		}
		return nil, err
	}
	// The bounded retry budget is exhausted — every generated number collided.
	return nil, &core.InvalidToolError{Message: core.MsgToolInventoryNumberCollision}
}

// UpdateTool replaces one ACTIVE tool's fields and refreshes updated_at
// (UPDATE_CLEAR_OVERRIDE / UPDATE_INVENTORY): an EMPTY schedule override CLEARS
// the stored override (schedule_id NULL → the tool inherits its type's default
// again, AD-5). The inventory number REPLACES the stored value (the core
// guarantees it is non-empty + bounded + unique case-insensitively among active
// tools). Attributes follow the shared JSONB contract (Story 4.4): a NIL map
// (absent field) leaves the stored JSONB UNCHANGED (the SQL
// `attributes = COALESCE($6, attributes)` keep), an explicit `{}` clears it and
// a non-empty object replaces it. Returns core.ErrToolNotFound when the id does
// not exist OR the row is already archived (the SQL's `archived_at IS NULL`
// guard affects zero rows then). An EXACT new name already held by an ARCHIVED
// row trips the DB UNIQUE constraint and is mapped to the German duplicate-name
// 400; an EXACT inventory number already held by ANY row (active or archived —
// the Story 4.5 import backstop) trips the tools_inventory_number_key UNIQUE
// index and is mapped to the German duplicate-inventory 400; a DB-level FK
// violation is mapped to the German 400 — never a raw 500.
func (r *Repository) UpdateTool(ctx context.Context, tool *core.Tool) (*core.Tool, error) {
	uid, err := parseOptionalUUID(tool.ID)
	if err != nil {
		return nil, core.ErrToolNotFound
	}
	toolTypeID, err := parseToolTypeID(tool.ToolTypeID)
	if err != nil {
		return nil, err
	}
	schedule, err := parseOptionalUUID(tool.ScheduleID)
	if err != nil {
		return nil, err
	}
	attrs, err := marshalUpdateAttributes(tool.Attributes)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.UpdateTool(ctx, UpdateToolParams{
		ID:              uid,
		Name:            tool.Name,
		ToolTypeID:      toolTypeID,
		ScheduleID:      schedule,
		InventoryNumber: tool.InventoryNumber,
		Attributes:      attrs,
	})
	if isUniqueViolation(err) {
		if isInventoryNumberCollision(err) {
			// An EXACT reuse of an inventory number (active OR archived — the
			// archived number stays taken) trips the UNIQUE index; the core's
			// case-insensitive active guard cannot see an archived row.
			return nil, &core.InvalidToolError{Message: core.MsgToolInventoryNumberTaken}
		}
		return nil, &core.InvalidToolError{Message: core.MsgToolNameTaken}
	}
	if isForeignKeyViolation(err) {
		// Same race as create: the type/override referenced by this update
		// vanished between the core check and this update → German 400.
		return nil, &core.InvalidToolError{Message: core.MsgToolReferencedGone}
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolNotFound
	}
	if err != nil {
		return nil, err
	}
	return toolFromUpdateRow(row), nil
}

// ArchiveTool soft-archives one tool (ARCHIVE): archived_at is set, the row
// leaves the active list. Returns core.ErrToolNotFound when the id does not
// exist OR the row is already archived.
func (r *Repository) ArchiveTool(ctx context.Context, id string) (*core.Tool, error) {
	uid, err := parseOptionalUUID(id)
	if err != nil {
		return nil, core.ErrToolNotFound
	}
	row, err := r.queries.ArchiveTool(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolNotFound
	}
	if err != nil {
		return nil, err
	}
	return toolFromArchiveRow(row), nil
}

// ListTools reads the ACTIVE tool catalog, oldest first, each with its tool
// type's display name (GET_LIST). Archived rows (archived_at IS NOT NULL)
// never appear; a tool WITHOUT an override reads back an empty ScheduleID
// (inherit the type default, AD-5).
func (r *Repository) ListTools(ctx context.Context) ([]*core.Tool, error) {
	rows, err := r.queries.ListTools(ctx)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Tool{}, nil
	}
	out := make([]*core.Tool, 0, len(rows))
	for i := range rows {
		out = append(out, toolFromListRow(rows[i]))
	}
	return out, nil
}

// ToolExistsActive is the lean update-path existence check: it reports whether
// the id exists AND is still active, without fetching the row (which the
// update pre-check does not use). A missing, malformed or already-archived id
// reports false (the surface treats all three as non-existent, ErrToolNotFound).
func (r *Repository) ToolExistsActive(ctx context.Context, id string) (bool, error) {
	uid, err := parseToolTypeID(id)
	if err != nil {
		return false, nil
	}
	return r.queries.ToolExistsActive(ctx, uid)
}

// GetToolWithTypeQualification is the lean inspection-start read (Story 5.1,
// FR-11/AD-7): it returns the ACTIVE tool plus its type's
// required_qualification_id and inspection_mode (intra-module JOIN on
// Tool-owned tool_types). A missing, malformed or already-archived id — OR a
// tool whose type is itself archived — answers core.ErrToolNotFound (the
// `archived_at IS NULL` guards affect zero rows then — the row is non-existent
// to the surface). A type with NO required qualification maps to an EMPTY
// string (the SQL NULL → "" semantics are made explicit here, never an
// incidental zero-UUID).
func (r *Repository) GetToolWithTypeQualification(ctx context.Context, id string) (*core.ToolWithTypeQualification, error) {
	uid, err := parseOptionalUUID(id)
	if err != nil {
		return nil, core.ErrToolNotFound
	}
	row, err := r.queries.GetToolWithTypeQualification(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolNotFound
	}
	if err != nil {
		return nil, err
	}
	requiredQualificationID := ""
	if row.RequiredQualificationID.Valid {
		requiredQualificationID = row.RequiredQualificationID.String()
	}
	return &core.ToolWithTypeQualification{
		ID:                      row.ID.String(),
		Name:                    row.Name,
		ToolTypeID:              row.ToolTypeID.String(),
		ToolTypeName:            row.ToolTypeName,
		RequiredQualificationID: requiredQualificationID,
		InspectionMode:          row.InspectionMode,
		ScheduleID:              row.ScheduleID.String(),
		DefaultScheduleID:       row.DefaultScheduleID.String(),
		ChecklistItems:          r.checklistItemsForType(ctx, row.ToolTypeID),
	}, nil
}

// checklistItemsForType loads the ordered checklist items of a tool type (Story
// 5.2 mode-aware start): a read failure is surfaced (the surface needs the
// items to render a checklist inspection; a silent empty list would show a
// checklist with no points).
func (r *Repository) checklistItemsForType(ctx context.Context, toolTypeID pgtype.UUID) []core.ToolTypeChecklistItem {
	itemRows, err := r.queries.GetToolTypeChecklistItems(ctx, toolTypeID)
	if err != nil {
		// The query returns rows or an error; a failure here is logged by the
		// caller's wrap. Fall back to an empty list so the start still resolves
		// eligibility — the missing items surface in the inspection screen's
		// empty-checklist state rather than failing the whole start.
		return nil
	}
	return checklistItemsFromRows(itemRows)
}

// toolFromRow maps an sqlc tool row (already JOINed with its type name) to the
// domain value. The stored attributes jsonb is unmarshalled into the map
// (default '{}'); a malformed non-object value surfaces as a clear error rather
// than a silent drop. ArchivedAt is nil for an active row, set after
// soft-archive.
func toolFromRow(row CreateToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromListRow is the ListTools variant (ListToolsRow is a distinct sqlc
// struct with the identical shape). It additionally carries the tool type's
// DEFAULT schedule id (Story 6.1: the dashboard's AD-5 interval-resolution
// input, via the Tool-owned JOIN).
func toolFromListRow(row ListToolsRow) *core.Tool {
	tool := toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
	tool.DefaultScheduleID = row.DefaultScheduleID.String()
	return tool
}

// toolFromUpdateRow is the UpdateTool variant (UpdateToolRow is a distinct
// sqlc struct with the identical shape).
func toolFromUpdateRow(row UpdateToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromArchiveRow is the ArchiveTool variant (ArchiveToolRow is a distinct
// sqlc struct with the identical shape).
func toolFromArchiveRow(row ArchiveToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromToolRow is the shared mapping for the four identical sqlc row shapes.
func toolFromToolRow(
	id pgtype.UUID,
	name string,
	toolTypeID pgtype.UUID,
	toolTypeName string,
	scheduleID pgtype.UUID,
	inventoryNumber string,
	attributes []byte,
	archivedAt pgtype.Timestamptz,
	createdAt, updatedAt pgtype.Timestamptz,
) *core.Tool {
	tool := &core.Tool{
		ID:              id.String(),
		Name:            name,
		ToolTypeID:      toolTypeID.String(),
		ToolTypeName:    toolTypeName,
		ScheduleID:      scheduleID.String(),
		InventoryNumber: inventoryNumber,
		Attributes:      map[string]any{},
		CreatedAt:       createdAt.Time,
		UpdatedAt:       updatedAt.Time,
	}
	if archivedAt.Valid {
		t := archivedAt.Time
		tool.ArchivedAt = &t
	}
	if len(attributes) > 0 {
		var attrs map[string]any
		if err := json.Unmarshal(attributes, &attrs); err != nil {
			// The jsonb column rejects syntactically invalid JSON, so a
			// "malformed" value is a valid non-object shape written
			// out-of-band; surface it as a clear error, never a crash or a
			// silent data-loss read (Story 4.4 boundary).
			tool.Attributes = map[string]any{"_unparseable": string(attributes)}
			return tool
		}
		if attrs != nil {
			tool.Attributes = attrs
		}
	}
	return tool
}

// marshalToolAttributes encodes the attributes map for the jsonb column on the
// CREATE paths (Story 4.4, FR-10/AD-3): a nil map (or an empty one) encodes as
// '{}' so the stored value is always a JSON object (the DB default when the
// column is omitted — an absent create field). Update paths use
// marshalUpdateAttributes, which encodes a nil map as SQL NULL so the SQL
// COALESCE keeps the stored value ("absent = unchanged").
func marshalToolAttributes(attrs map[string]any) ([]byte, error) {
	if attrs == nil {
		return []byte("{}"), nil
	}
	raw, err := json.Marshal(attrs)
	if err != nil {
		return nil, err
	}
	if len(raw) == 0 || string(raw) == "null" {
		return []byte("{}"), nil
	}
	return raw, nil
}

// marshalUpdateAttributes encodes the attributes map for the jsonb column on
// the UPDATE paths (Story 4.4, FR-10/AD-3): a NIL map encodes as SQL NULL so
// the update's `attributes = COALESCE($6, attributes)` KEEPS the stored value
// ("absent = unchanged"). An empty map encodes as '{}' (the explicit clear)
// and a non-empty object as-is.
func marshalUpdateAttributes(attrs map[string]any) ([]byte, error) {
	if attrs == nil {
		return nil, nil
	}
	return marshalToolAttributes(attrs)
}

// parseOptionalUUID parses a uuid FK that may be EMPTY (→ pgtype.UUID{} →
// SQL NULL), treating a malformed id as core.ErrToolNotFound. It is the
// generic sibling of parseToolTypeID — used for the tool surface's non-type FKs
// (the tool's own id and the optional schedule override) so the tool-type-named
// helper is only used where the FK is genuinely a tool type.
func parseOptionalUUID(id string) (pgtype.UUID, error) {
	if strings.TrimSpace(id) == "" {
		return pgtype.UUID{}, nil
	}
	var uid pgtype.UUID
	if err := uid.Scan(id); err != nil {
		return pgtype.UUID{}, core.ErrToolNotFound
	}
	return uid, nil
}

// uuidSlice parses a list of canonical UUID strings into pgtype.UUID values
// (Story 3.3 DSGVO export tool-name resolution). A malformed id returns an
// error; the empty input returns an empty slice.
func uuidSlice(ids []string) ([]pgtype.UUID, error) {
	out := make([]pgtype.UUID, 0, len(ids))
	for _, id := range ids {
		var uid pgtype.UUID
		if err := uid.Scan(id); err != nil {
			return nil, err
		}
		out = append(out, uid)
	}
	return out, nil
}

// isInventoryNumberCollision reports whether err is a UNIQUE-constraint
// violation on the tools_inventory_number_key index (Story 4-3b): the
// auto-assigned number collided with a manually-entered one, or an update
// reused a number held by ANOTHER row (active or archived — the Story 4.5
// import backstop). The CreateTool retry loop branches on it; UpdateTool maps
// it to the German duplicate-inventory 400.
func isInventoryNumberCollision(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505" && pgErr.ConstraintName == "tools_inventory_number_key"
}

// Compile-time check: the repository satisfies the core ToolStore port.
var _ core.ToolStore = (*Repository)(nil)

// ============================================================================
// Bulk CSV import (Story 4.5, FR-9/FR-23): the SET-PARTITIONED batch store
// methods — ONE multi-row INSERT / UPDATE per set, each in its own
// transaction, so a large file imports in ~2-4 round-trips + 2 commits no
// matter the row count. A concurrent race is absorbed per-row (ON CONFLICT /
// per-row fallback), never a wholesale abort.
// ============================================================================

// pgxScanner is the tiny Scan-only subset shared by pgx.Row and pgx.Rows, so
// one row mapper serves the batch queries' rows AND the per-row QueryRow.
type pgxScanner interface {
	Scan(dest ...any) error
}

// toolFromBatchRow scans one 10-column Tool row (the batch INSERT/UPDATE
// RETURNING + JOIN shape, identical to the sqlc row shapes) into the domain
// value.
func toolFromBatchRow(row pgxScanner) (*core.Tool, error) {
	var id, toolTypeID, scheduleID pgtype.UUID
	var name, toolTypeName string
	var inventoryNumber string
	var attributes []byte
	var archivedAt pgtype.Timestamptz
	var createdAt, updatedAt pgtype.Timestamptz
	if err := row.Scan(&id, &name, &toolTypeID, &toolTypeName, &scheduleID, &inventoryNumber, &attributes, &archivedAt, &createdAt, &updatedAt); err != nil {
		return nil, err
	}
	return toolFromToolRow(id, name, toolTypeID, toolTypeName, scheduleID, inventoryNumber, attributes, archivedAt, createdAt, updatedAt), nil
}

// createToolsBatchSQL is the set-partitioned CREATE: ONE multi-row INSERT over
// the unnest'd arrays with `ON CONFLICT DO NOTHING` (any unique violation — a
// concurrent name/inventory grab — skips ONLY that row) and `RETURNING` the
// inserted rows JOINed with their type name. The inventory number honors an
// EXPLICIT cell (COALESCE) and auto-assigns '<prefix> || zero-padded nextval'
// in-SQL for an absent one — exactly the single-row CreateTool semantics,
// batched. The sequence is consumed only for rows WITHOUT an explicit number
// (COALESCE short-circuits nextval).
const createToolsBatchSQL = `
WITH ins AS (
    INSERT INTO tools (name, tool_type_id, schedule_id, inventory_number, attributes)
    SELECT n,
           NULLIF(tt, '')::uuid,
           NULLIF(sc, '')::uuid,
           COALESCE(NULLIF(inv, ''), $1 || lpad(nextval('tools_inventory_number_seq')::text, $2, '0')),
           attr::jsonb
    FROM unnest($3::text[], $4::text[], $5::text[], $6::text[], $7::text[]) AS t(n, tt, sc, inv, attr)
    ON CONFLICT DO NOTHING
    RETURNING id, name, tool_type_id, schedule_id, inventory_number, attributes, archived_at, created_at, updated_at
)
SELECT i.id, i.name, i.tool_type_id, tt.name AS tool_type_name, i.schedule_id, i.inventory_number, i.attributes, i.archived_at, i.created_at, i.updated_at
FROM ins i
JOIN tool_types tt ON tt.id = i.tool_type_id
`

// updateToolsBatchSQL is the set-partitioned UPDATE: ONE multi-row
// `UPDATE ... FROM (VALUES ...)` that applies ONLY the fields a row PROVIDES —
// tool_type_id always; schedule_id / inventory_number via `CASE WHEN provided
// THEN value ELSE tools.<col> END` (an absent cell PRESERVES the stored
// value). attributes/name/archived_at are never in the SET — the absolute
// no-data-loss rule (FR-9). The `archived_at IS NULL` guard keeps a
// concurrently-archived tool out (its row simply misses the RETURNING → the
// repo reports it per-index as a race).
const updateToolsBatchSQL = `
WITH input AS (
    SELECT * FROM unnest(
        $1::uuid[], $2::uuid[], $3::text[], $4::bool[], $5::text[], $6::bool[]
    ) AS t(tool_id, tool_type_id, schedule_id, schedule_provided, inventory_number, inventory_provided)
),
updated AS (
    UPDATE tools
    SET tool_type_id = input.tool_type_id,
        schedule_id = CASE WHEN input.schedule_provided THEN input.schedule_id::uuid ELSE tools.schedule_id END,
        inventory_number = CASE WHEN input.inventory_provided THEN input.inventory_number ELSE tools.inventory_number END,
        updated_at = now()
    FROM input
    WHERE tools.id = input.tool_id AND tools.archived_at IS NULL
    RETURNING tools.id, tools.name, tools.tool_type_id, tools.schedule_id, tools.inventory_number, tools.attributes, tools.archived_at, tools.created_at, tools.updated_at
)
SELECT u.id, u.name, u.tool_type_id, tt.name AS tool_type_name, u.schedule_id, u.inventory_number, u.attributes, u.archived_at, u.created_at, u.updated_at
FROM updated u
JOIN tool_types tt ON tt.id = u.tool_type_id
`

// updateToolImportRowSQL is the per-row UPDATE used by the batch fallback (a
// constraint violation isolated a row) — same no-data-loss CASE semantics, one
// row at a time, inside the SAME transaction.
const updateToolImportRowSQL = `
WITH updated AS (
    UPDATE tools
    SET tool_type_id = $1,
        schedule_id = CASE WHEN $2 THEN $3 ELSE tools.schedule_id END,
        inventory_number = CASE WHEN $4 THEN $5 ELSE tools.inventory_number END,
        updated_at = now()
    WHERE tools.id = $6 AND tools.archived_at IS NULL
    RETURNING id, name, tool_type_id, schedule_id, inventory_number, attributes, archived_at, created_at, updated_at
)
SELECT u.id, u.name, u.tool_type_id, tt.name AS tool_type_name, u.schedule_id, u.inventory_number, u.attributes, u.archived_at, u.created_at, u.updated_at
FROM updated u
JOIN tool_types tt ON tt.id = u.tool_type_id
`

// CreateToolsBatch persists a SET of new tools in ONE batched multi-row INSERT
// (Story 4.5 set-partitioned execution): explicit inventory numbers honored,
// absent ones auto-assigned in-SQL, `ON CONFLICT DO NOTHING` skipping ONLY the
// colliding rows (NEW_BATCH_RACE — reported per-index as core.ErrToolImportCollision)
// while the rest commit — the batch never aborts wholesale. A non-unique
// constraint violation (an FK race: the type archived between the core check
// and this insert) rolls back and falls back to per-row CreateTool calls in the
// SAME transaction to isolate the offender. Returns the created tools (one per
// successfully inserted input) + the per-index failure map. The created slice
// is NOT order-guaranteed: PostgreSQL does not guarantee RETURNING order over
// the multi-row INSERT, so callers must treat it as a SET (the core attributes
// batch failures by name, never by position).
func (r *Repository) CreateToolsBatch(ctx context.Context, tools []*core.Tool, inventoryPrefix string, inventoryWidth int) ([]*core.Tool, map[int]error, error) {
	if len(tools) == 0 {
		return []*core.Tool{}, map[int]error{}, nil
	}
	names := make([]string, len(tools))
	typeIDs := make([]string, len(tools))
	scheduleIDs := make([]string, len(tools))
	inventories := make([]string, len(tools))
	attrs := make([]string, len(tools))
	for i, t := range tools {
		names[i] = t.Name
		typeID, err := parseToolTypeID(t.ToolTypeID)
		if err != nil {
			return nil, nil, err
		}
		typeIDs[i] = typeID.String()
		schedule, err := parseOptionalUUID(t.ScheduleID)
		if err != nil {
			return nil, nil, err
		}
		if schedule.Valid {
			scheduleIDs[i] = schedule.String()
		}
		inventories[i] = t.InventoryNumber
		raw, err := marshalToolAttributes(t.Attributes)
		if err != nil {
			return nil, nil, err
		}
		attrs[i] = string(raw)
	}

	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	created, failed, err := r.createToolsBatchInTx(ctx, tx, names, typeIDs, scheduleIDs, inventories, attrs, inventoryPrefix, inventoryWidth, tools)
	if err != nil {
		return nil, nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return created, failed, nil
}

// createToolsBatchInTx runs the batch INSERT inside an open transaction. A
// savepoint lets a non-unique constraint violation roll back ONLY the failed
// statement and continue with the per-row fallback in the same transaction.
func (r *Repository) createToolsBatchInTx(ctx context.Context, tx pgx.Tx, names, typeIDs, scheduleIDs, inventories, attrs []string, inventoryPrefix string, inventoryWidth int, tools []*core.Tool) ([]*core.Tool, map[int]error, error) {
	if _, err := tx.Exec(ctx, "SAVEPOINT tools_import_create_batch"); err != nil {
		return nil, nil, err
	}
	args := []any{inventoryPrefix, inventoryWidth, names, typeIDs, scheduleIDs, inventories, attrs}
	rows, err := tx.Query(ctx, createToolsBatchSQL, args...)
	if err != nil {
		created, failed, fallbackErr := r.createToolsBatchFallback(ctx, tx, tools, inventoryPrefix, inventoryWidth)
		return created, failed, fallbackErr
	}
	created := []*core.Tool{}
	createdNames := map[string]struct{}{}
	for rows.Next() {
		t, scanErr := toolFromBatchRow(rows)
		if scanErr != nil {
			rows.Close()
			created, failed, fallbackErr := r.createToolsBatchFallback(ctx, tx, tools, inventoryPrefix, inventoryWidth)
			return created, failed, fallbackErr
		}
		created = append(created, t)
		createdNames[t.Name] = struct{}{}
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		created, failed, fallbackErr := r.createToolsBatchFallback(ctx, tx, tools, inventoryPrefix, inventoryWidth)
		return created, failed, fallbackErr
	}
	// Names are unique within the newSet (the core deduped within-file), so a
	// missing RETURNING name = a row skipped by ON CONFLICT (a concurrent race).
	failed := map[int]error{}
	for i, t := range tools {
		if _, ok := createdNames[t.Name]; !ok {
			failed[i] = core.ErrToolImportCollision
		}
	}
	return created, failed, nil
}

// createToolsBatchFallback rolls back to the savepoint and persists each row
// individually in the SAME transaction (queries.WithTx) — the FK-race path: the
// offending row surfaces its German error, the rest commit.
func (r *Repository) createToolsBatchFallback(ctx context.Context, tx pgx.Tx, tools []*core.Tool, inventoryPrefix string, inventoryWidth int) ([]*core.Tool, map[int]error, error) {
	if _, err := tx.Exec(ctx, "ROLLBACK TO SAVEPOINT tools_import_create_batch"); err != nil {
		return nil, nil, err
	}
	qt := r.queries.WithTx(tx)
	created := []*core.Tool{}
	failed := map[int]error{}
	for i, t := range tools {
		// Each row runs behind its OWN savepoint so a failing row (an FK race)
		// does not abort the transaction for the rows after it.
		if _, err := tx.Exec(ctx, "SAVEPOINT tools_import_row"); err != nil {
			return nil, nil, err
		}
		typeID, err := parseToolTypeID(t.ToolTypeID)
		if err != nil {
			failed[i] = err
			continue
		}
		schedule, err := parseOptionalUUID(t.ScheduleID)
		if err != nil {
			failed[i] = err
			continue
		}
		rawAttrs, err := marshalToolAttributes(t.Attributes)
		if err != nil {
			failed[i] = err
			continue
		}
		row, err := qt.CreateTool(ctx, CreateToolParams{
			Name:            t.Name,
			ToolTypeID:      typeID,
			ScheduleID:      schedule,
			Attributes:      rawAttrs,
			InventoryPrefix: pgtype.Text{String: inventoryPrefix, Valid: inventoryPrefix != ""},
			InventoryWidth:  int32(inventoryWidth),
		})
		if err != nil {
			if _, rbErr := tx.Exec(ctx, "ROLLBACK TO SAVEPOINT tools_import_row"); rbErr != nil {
				return nil, nil, rbErr
			}
			failed[i] = err
			continue
		}
		if _, rbErr := tx.Exec(ctx, "RELEASE SAVEPOINT tools_import_row"); rbErr != nil {
			return nil, nil, rbErr
		}
		created = append(created, toolFromRow(row))
	}
	return created, failed, nil
}

// UpdateToolsBatch persists a SET of updates in ONE batched multi-row UPDATE
// (Story 4.5 set-partitioned execution): tool_type_id always; schedule_id /
// inventory_number only when the row PROVIDES them (CASE WHEN provided) — an
// absent cell PRESERVES the stored value, attributes/name/archived_at are
// NEVER touched (the absolute no-data-loss rule, FR-9). A constraint violation
// (an explicit inventory colliding with an archived row, or an FK race)
// rolls back the batch and applies each row individually in the SAME
// transaction to isolate the offender. Returns the updated tools (one per
// successful update, in input order) + a per-index error slice (nil = success).
func (r *Repository) UpdateToolsBatch(ctx context.Context, updates []core.ToolImportUpdate) ([]*core.Tool, []error, error) {
	if len(updates) == 0 {
		return []*core.Tool{}, []error{}, nil
	}
	toolIDs := make([]string, len(updates))
	typeIDs := make([]string, len(updates))
	scheduleIDs := make([]string, len(updates))
	scheduleProvided := make([]bool, len(updates))
	inventories := make([]string, len(updates))
	inventoryProvided := make([]bool, len(updates))
	for i, u := range updates {
		toolIDs[i] = u.ToolID
		typeID, err := parseToolTypeID(u.ToolTypeID)
		if err != nil {
			return nil, nil, err
		}
		typeIDs[i] = typeID.String()
		if u.ScheduleProvided {
			schedule, err := parseOptionalUUID(u.ScheduleID)
			if err != nil {
				return nil, nil, err
			}
			scheduleIDs[i] = schedule.String()
		}
		scheduleProvided[i] = u.ScheduleProvided
		inventories[i] = u.InventoryNumber
		inventoryProvided[i] = u.InventoryProvided
	}

	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	updated, errs, err := r.updateToolsBatchInTx(ctx, tx, toolIDs, typeIDs, scheduleIDs, scheduleProvided, inventories, inventoryProvided, updates)
	if err != nil {
		return nil, nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return updated, errs, nil
}

// updateToolsBatchInTx runs the batch UPDATE inside an open transaction; a
// constraint violation rolls back to the savepoint and applies each row
// individually in the same transaction (updateToolsBatchFallback).
func (r *Repository) updateToolsBatchInTx(ctx context.Context, tx pgx.Tx, toolIDs, typeIDs, scheduleIDs []string, scheduleProvided []bool, inventories []string, inventoryProvided []bool, updates []core.ToolImportUpdate) ([]*core.Tool, []error, error) {
	if _, err := tx.Exec(ctx, "SAVEPOINT tools_import_update_batch"); err != nil {
		return nil, nil, err
	}
	args := []any{toolIDs, typeIDs, scheduleIDs, scheduleProvided, inventories, inventoryProvided}
	rows, err := tx.Query(ctx, updateToolsBatchSQL, args...)
	if err != nil {
		updated, errs, fallbackErr := r.updateToolsBatchFallback(ctx, tx, updates)
		return updated, errs, fallbackErr
	}
	updatedByID := map[string]*core.Tool{}
	for rows.Next() {
		t, scanErr := toolFromBatchRow(rows)
		if scanErr != nil {
			rows.Close()
			updated, errs, fallbackErr := r.updateToolsBatchFallback(ctx, tx, updates)
			return updated, errs, fallbackErr
		}
		updatedByID[t.ID] = t
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		updated, errs, fallbackErr := r.updateToolsBatchFallback(ctx, tx, updates)
		return updated, errs, fallbackErr
	}
	updated := []*core.Tool{}
	errs := make([]error, len(updates))
	for i, u := range updates {
		if t, ok := updatedByID[u.ToolID]; ok {
			updated = append(updated, t)
			continue
		}
		// The UPDATE affected zero rows — the tool was ARCHIVED between the core
		// list and this write (the WHERE archived_at IS NULL guard). A race →
		// generic "bereits vergeben" row error, never an abort.
		errs[i] = core.ErrToolImportCollision
	}
	return updated, errs, nil
}

// updateToolsBatchFallback rolls back to the savepoint and applies each update
// individually in the SAME transaction: the offending row surfaces its German
// error (duplicate inventory / referenced-gone), the rest commit.
func (r *Repository) updateToolsBatchFallback(ctx context.Context, tx pgx.Tx, updates []core.ToolImportUpdate) ([]*core.Tool, []error, error) {
	if _, err := tx.Exec(ctx, "ROLLBACK TO SAVEPOINT tools_import_update_batch"); err != nil {
		return nil, nil, err
	}
	updated := []*core.Tool{}
	errs := make([]error, len(updates))
	for i := range updates {
		// Each row runs behind its OWN savepoint so a failing row (a unique
		// violation / FK race) does not abort the transaction for the rows
		// after it.
		if _, err := tx.Exec(ctx, "SAVEPOINT tools_import_row"); err != nil {
			return nil, nil, err
		}
		t, err := r.updateToolImportRow(ctx, tx, updates[i])
		if err != nil {
			if _, rbErr := tx.Exec(ctx, "ROLLBACK TO SAVEPOINT tools_import_row"); rbErr != nil {
				return nil, nil, rbErr
			}
			errs[i] = err
			continue
		}
		if _, rbErr := tx.Exec(ctx, "RELEASE SAVEPOINT tools_import_row"); rbErr != nil {
			return nil, nil, rbErr
		}
		updated = append(updated, t)
	}
	return updated, errs, nil
}

// updateToolImportRow applies ONE update row (the per-row fallback) with the
// same no-data-loss semantics. A UNIQUE violation on the inventory index maps
// to the German duplicate-inventory 400 (the archived-number backstop); an FK
// violation maps to the German referenced-gone 400; a missing/archived row is
// a race (ErrToolImportCollision).
func (r *Repository) updateToolImportRow(ctx context.Context, tx pgx.Tx, u core.ToolImportUpdate) (*core.Tool, error) {
	toolID, err := parseOptionalUUID(u.ToolID)
	if err != nil {
		return nil, core.ErrToolImportCollision
	}
	typeID, err := parseToolTypeID(u.ToolTypeID)
	if err != nil {
		return nil, err
	}
	// When the schedule is NOT provided the value is ignored by the CASE (the
	// stored value is preserved); a not-valid pgtype.UUID binds as SQL NULL so
	// the statement never trips an empty-uuid cast error.
	schedule, err := parseOptionalUUID(u.ScheduleID)
	if err != nil {
		return nil, err
	}
	row := tx.QueryRow(ctx, updateToolImportRowSQL, typeID, u.ScheduleProvided, schedule, u.InventoryProvided, u.InventoryNumber, toolID)
	t, err := toolFromBatchRow(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, core.ErrToolImportCollision
		}
		if isUniqueViolation(err) {
			if isInventoryNumberCollision(err) {
				return nil, &core.InvalidToolError{Message: core.MsgToolInventoryNumberTaken}
			}
			return nil, &core.InvalidToolError{Message: core.MsgToolNameTaken}
		}
		if isForeignKeyViolation(err) {
			return nil, &core.InvalidToolError{Message: core.MsgToolReferencedGone}
		}
		return nil, err
	}
	return t, nil
}

// FindToolCollisions is the Story 4.5 collision pre-check (the 4-3b backstop):
// it reports which input names/inventory numbers are already held by ANY tools
// row (ACTIVE AND ARCHIVED). Names match EXACTLY; inventory matches
// case-insensitively (the caller passes the lowercased inputs; the returned
// hit keys are lowercased too). Rows are filtered against the exact input sets
// so a row matched on the OTHER column is never misreported.
func (r *Repository) FindToolCollisions(ctx context.Context, names, inventoryNumbers []string) (map[string]struct{}, map[string]struct{}, error) {
	nameHits := map[string]struct{}{}
	inventoryHits := map[string]struct{}{}
	if len(names) == 0 && len(inventoryNumbers) == 0 {
		return nameHits, inventoryHits, nil
	}
	nameSet := make(map[string]struct{}, len(names))
	for _, n := range names {
		nameSet[n] = struct{}{}
	}
	lowerInv := make([]string, 0, len(inventoryNumbers))
	invSet := make(map[string]struct{}, len(inventoryNumbers))
	for _, inv := range inventoryNumbers {
		l := strings.ToLower(inv)
		lowerInv = append(lowerInv, l)
		invSet[l] = struct{}{}
	}
	rows, err := r.queries.FindToolCollisions(ctx, FindToolCollisionsParams{Names: names, InventoryNumbers: lowerInv})
	if err != nil {
		return nil, nil, err
	}
	for _, row := range rows {
		if _, ok := nameSet[row.Name]; ok {
			nameHits[row.Name] = struct{}{}
		}
		if _, ok := invSet[row.InventoryNumber]; ok {
			inventoryHits[row.InventoryNumber] = struct{}{}
		}
	}
	return nameHits, inventoryHits, nil
}
