package postgres

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/tools/core"
)

// Tool-type store implementation (Story 4.2, FR-8/FR-10/FR-23/AD-10):
// list-active (incl. ordered checklist items) / create-with-items / update
// with FULL item replacement / archive over the Tool-owned tool_types +
// tool_type_checklist_items tables. Soft archive only — no hard delete (FK
// history preserved). The `archived_at IS NULL` guard on update/archive makes
// an already-archived row non-existent to the surface (ErrToolTypeNotFound).
// Create/update run the item writes in ONE transaction (delete-then-insert,
// separate statements — Story 2.5 lesson), so a failed half-write never leaves
// a mixed item state.

// Repository wraps the sqlc-generated Queries to implement core.ToolTypeStore.
type Repository struct {
	queries *Queries
}

// NewRepository creates a new postgres tool-type repository.
func NewRepository(queries *Queries) *Repository {
	return &Repository{queries: queries}
}

// ListToolTypes reads the ACTIVE tool-type catalog, oldest first, each with
// its ordered checklist items (GET_LIST). Archived rows (archived_at IS NOT
// NULL) never appear; pass_fail types carry an empty item list.
func (r *Repository) ListToolTypes(ctx context.Context) ([]*core.ToolType, error) {
	rows, err := r.queries.ListToolTypes(ctx)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.ToolType{}, nil
	}

	ids := make([]pgtype.UUID, 0, len(rows))
	for i := range rows {
		ids = append(ids, rows[i].ID)
	}
	itemRows, err := r.queries.ListToolTypeChecklistItems(ctx, ids)
	if err != nil {
		return nil, err
	}
	itemsByType := groupChecklistItems(itemRows)

	out := make([]*core.ToolType, 0, len(rows))
	for i := range rows {
		out = append(out, toolTypeFromRow(rows[i], itemsByType[rows[i].ID]))
	}
	return out, nil
}

// ToolTypeExistsActive is the lean update-path existence check: it reports
// whether the id exists AND is still active, without fetching the checklist
// items (which the update pre-check does not use). A missing, malformed or
// already-archived id reports false (the surface treats all three as
// non-existent, ErrToolTypeNotFound).
func (r *Repository) ToolTypeExistsActive(ctx context.Context, id string) (bool, error) {
	uid, err := parseToolTypeID(id)
	if err != nil {
		return false, nil
	}
	return r.queries.ToolTypeExistsActive(ctx, uid)
}

// CreateToolType inserts a tool type AND its ordered checklist items in ONE
// transaction (CREATE_VALID). The id is generated by the DB (uuidv7); the
// attributes jsonb column stays at the DB default '{}'. Duplicate-name
// semantics (coherent with the core's active-only case-insensitive guard):
// an EXACT name reuse of an archived row (invisible to the core guard) trips
// the DB UNIQUE constraint and is mapped to the German duplicate-name 400; a
// CASE-VARIANT of an archived name is deliberately allowed (the UNIQUE is
// case-sensitive). A DB-level FK violation (the referenced schedule/
// qualification vanished between the port check and this insert) is mapped to
// the German 400 — never a raw pg error / 500.
func (r *Repository) CreateToolType(ctx context.Context, toolType *core.ToolType) (*core.ToolType, error) {
	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after Commit

	q := r.queries.WithTx(tx)

	schedule, err := parseToolTypeID(toolType.DefaultScheduleID)
	if err != nil {
		return nil, err
	}
	qualification, err := parseToolTypeID(toolType.RequiredQualificationID)
	if err != nil {
		return nil, err
	}
	row, err := q.CreateToolType(ctx, CreateToolTypeParams{
		Name:                     toolType.Name,
		DefaultScheduleID:        schedule,
		RequiredQualificationID:  qualification,
		InspectionMode:           toolType.InspectionMode,
	})
	if isUniqueViolation(err) {
		return nil, &core.InvalidToolTypeError{Message: core.MsgToolTypeNameTaken}
	}
	if isForeignKeyViolation(err) {
		// A race between the core's port FK check and this insert (the
		// referenced schedule archived / qualification deleted meanwhile)
		// surfaces as SQLSTATE 23503 — map it to the German 400, never a raw
		// pg error / 500.
		return nil, &core.InvalidToolTypeError{Message: core.MsgToolTypeReferencedGone}
	}
	if err != nil {
		return nil, err
	}

	if err := insertToolTypeItems(ctx, q, row.ID, toolType.Items); err != nil {
		return nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	itemRows, err := r.queries.GetToolTypeChecklistItems(ctx, row.ID)
	if err != nil {
		return nil, err
	}
	return toolTypeFromRow(row, itemRows), nil
}

// UpdateToolType replaces one ACTIVE type's core fields AND its checklist items
// fully in ONE transaction (UPDATE_REPLACE_ITEMS): the existing items are
// deleted and the submitted ordered list re-inserted, updated_at refreshed.
// Returns core.ErrToolTypeNotFound when the id does not exist OR the row is
// already archived (the SQL's `archived_at IS NULL` guard affects zero rows
// then). An EXACT new name already held by an ARCHIVED row trips the DB UNIQUE
// constraint and is mapped to the German duplicate-name 400; a DB-level FK
// violation is mapped to the German 400 — never a raw 500.
func (r *Repository) UpdateToolType(ctx context.Context, toolType *core.ToolType) (*core.ToolType, error) {
	uid, err := parseToolTypeID(toolType.ID)
	if err != nil {
		return nil, core.ErrToolTypeNotFound
	}

	tx, err := r.beginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after Commit

	q := r.queries.WithTx(tx)

	schedule, err := parseToolTypeID(toolType.DefaultScheduleID)
	if err != nil {
		return nil, err
	}
	qualification, err := parseToolTypeID(toolType.RequiredQualificationID)
	if err != nil {
		return nil, err
	}
	row, err := q.UpdateToolType(ctx, UpdateToolTypeParams{
		ID:                      uid,
		Name:                    toolType.Name,
		DefaultScheduleID:       schedule,
		RequiredQualificationID: qualification,
		InspectionMode:          toolType.InspectionMode,
	})
	if isUniqueViolation(err) {
		return nil, &core.InvalidToolTypeError{Message: core.MsgToolTypeNameTaken}
	}
	if isForeignKeyViolation(err) {
		// Same race as create: a referenced schedule/qualification vanished
		// between the port check and this update → German 400, never a 500.
		return nil, &core.InvalidToolTypeError{Message: core.MsgToolTypeReferencedGone}
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolTypeNotFound
	}
	if err != nil {
		return nil, err
	}

	if err := q.DeleteToolTypeChecklistItems(ctx, uid); err != nil {
		return nil, err
	}
	if err := insertToolTypeItems(ctx, q, uid, toolType.Items); err != nil {
		return nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	itemRows, err := r.queries.GetToolTypeChecklistItems(ctx, uid)
	if err != nil {
		return nil, err
	}
	return toolTypeFromRow(row, itemRows), nil
}

// ArchiveToolType soft-archives one tool type (ARCHIVE): archived_at is set,
// the row leaves the active list. Returns core.ErrToolTypeNotFound when the id
// does not exist OR the row is already archived.
func (r *Repository) ArchiveToolType(ctx context.Context, id string) (*core.ToolType, error) {
	uid, err := parseToolTypeID(id)
	if err != nil {
		return nil, core.ErrToolTypeNotFound
	}
	row, err := r.queries.ArchiveToolType(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolTypeNotFound
	}
	if err != nil {
		return nil, err
	}
	itemRows, err := r.queries.GetToolTypeChecklistItems(ctx, uid)
	if err != nil {
		return nil, err
	}
	return toolTypeFromRow(row, itemRows), nil
}

// insertToolTypeItems writes the ordered checklist items of a tool type inside
// the caller's transaction. The position is the explicit array order the core
// assigned; pass_fail types (or an empty checklist) insert nothing.
func insertToolTypeItems(ctx context.Context, q *Queries, toolTypeID pgtype.UUID, items []core.ToolTypeChecklistItem) error {
	for _, item := range items {
		if err := q.InsertToolTypeChecklistItem(ctx, InsertToolTypeChecklistItemParams{
			ToolTypeID: toolTypeID,
			Position:   int32(item.Position),
			Label:      item.Label,
		}); err != nil {
			return err
		}
	}
	return nil
}

// groupChecklistItems buckets the fetched item rows by their tool_type_id so
// the repository can attach them to the fetched tool types in one round-trip.
func groupChecklistItems(rows []ToolTypeChecklistItem) map[pgtype.UUID][]ToolTypeChecklistItem {
	grouped := make(map[pgtype.UUID][]ToolTypeChecklistItem, len(rows))
	for i := range rows {
		id := rows[i].ToolTypeID
		grouped[id] = append(grouped[id], rows[i])
	}
	return grouped
}

// toolTypeFromRow maps an sqlc tool-type row (+ its ordered item rows) to the
// domain value. The stored attributes jsonb is unmarshalled into the map
// (default '{}'); a malformed non-object value surfaces as a clear error rather
// than a silent drop. ArchivedAt is nil for an active row, set after
// soft-archive.
func toolTypeFromRow(row ToolType, itemRows []ToolTypeChecklistItem) *core.ToolType {
	tt := &core.ToolType{
		ID:                      row.ID.String(),
		Name:                    row.Name,
		DefaultScheduleID:       row.DefaultScheduleID.String(),
		RequiredQualificationID: row.RequiredQualificationID.String(),
		InspectionMode:          row.InspectionMode,
		Attributes:              map[string]any{},
		Items:                   checklistItemsFromRows(itemRows),
		CreatedAt:               row.CreatedAt.Time,
		UpdatedAt:               row.UpdatedAt.Time,
	}
	if row.ArchivedAt.Valid {
		t := row.ArchivedAt.Time
		tt.ArchivedAt = &t
	}
	if len(row.Attributes) > 0 {
		var attrs map[string]any
		if err := json.Unmarshal(row.Attributes, &attrs); err != nil {
			// The jsonb column rejects syntactically invalid JSON, so a
			// "malformed" value is a valid non-object shape written
			// out-of-band; surface it as a clear error, never a crash or a
			// silent data-loss read (Story 4.4 boundary).
			tt.Attributes = map[string]any{"_unparseable": string(row.Attributes)}
			return tt
		}
		if attrs != nil {
			tt.Attributes = attrs
		}
	}
	return tt
}

// checklistItemsFromRows maps the ordered item rows to the domain items. The
// rows are already ordered by position (the SQL ORDER BY guarantees it).
func checklistItemsFromRows(rows []ToolTypeChecklistItem) []core.ToolTypeChecklistItem {
	if len(rows) == 0 {
		return []core.ToolTypeChecklistItem{}
	}
	items := make([]core.ToolTypeChecklistItem, 0, len(rows))
	for _, row := range rows {
		items = append(items, core.ToolTypeChecklistItem{
			ID:       row.ID.String(),
			Position: int(row.Position),
			Label:    row.Label,
		})
	}
	return items
}

// parseToolTypeID parses a URL-path uuidv7 into pgtype.UUID. A malformed id is
// treated as not-found (no existence hint to a caller).
func parseToolTypeID(id string) (pgtype.UUID, error) {
	var uid pgtype.UUID
	if err := uid.Scan(id); err != nil {
		return pgtype.UUID{}, core.ErrToolTypeNotFound
	}
	return uid, nil
}

// txBeginner is the subset of pgxpool.Pool that can open a transaction. The
// Queries handle is constructed over the pool (New(pool) in the composition
// root), so beginTx recovers it from the underlying DBTX without a separate
// constructor dependency.
type txBeginner interface {
	Begin(ctx context.Context) (pgx.Tx, error)
}

// beginTx opens a fresh transaction on the underlying pool. A Queries handle
// built over anything that is not transaction-capable (only conceivable in a
// unit test) surfaces a clear error instead of panicking.
func (r *Repository) beginTx(ctx context.Context) (pgx.Tx, error) {
	if r.queries == nil {
		return nil, errors.New("tools postgres: nil queries")
	}
	pool, ok := r.queries.db.(txBeginner)
	if !ok {
		return nil, errors.New("tools postgres: db handle does not support transactions")
	}
	return pool.Begin(ctx)
}

// isUniqueViolation reports whether err is a PostgreSQL unique-constraint
// violation (SQLSTATE 23505) — e.g. the tool_types.name UNIQUE constraint.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

// isForeignKeyViolation reports whether err is a PostgreSQL foreign-key
// violation (SQLSTATE 23503) — e.g. the tool_types.default_schedule_id /
// required_qualification_id FKs. The core validates the FKs through the
// modules' ports first; this is the DB backstop for the TOCTOU race.
func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}

// Compile-time check: the repository satisfies the core ToolTypeStore port.
var _ core.ToolTypeStore = (*Repository)(nil)