package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/saskia-peters/gear/internal/tools/core"
)

// maxInventoryNumberRetries is the bounded retry budget for the auto-assigned
// inventory number (Story 4-3b): when the INSERT computes a nextval that a
// MANUAL edit already consumed (a future sequence value), the UNIQUE index
// trips and the repository re-runs the INSERT — which computes a FRESH nextval
// in-SQL. After this many consecutive collisions the create fails with the
// German collision 400.
const maxInventoryNumberRetries = 3

// Tool store implementation (Story 4.3, FR-9/FR-10/AD-5/AD-10): list-active
// (each tool JOINed with its Tool-owned type name) / create / update (with
// override-clear → NULL) / archive over the Tool-owned `tools` table. Soft
// archive only — no hard delete (FK history preserved). The `archived_at IS
// NULL` guard on update/archive makes an already-archived row non-existent to
// the surface (ErrToolNotFound). The tool's type FK is intra-module (Tool-owned
// tool_types); the optional schedule override is a first-class FK to the
// Admin-owned schedules catalog (validated at the core against the
// SchedulesPort) — an empty override is stored as SQL NULL (inherit the type
// default, AD-5), mirroring the optional-qualification precedent (parseToolTypeID
// empty → pgtype.UUID{} → NULL).

// CreateTool inserts one tool (CREATE_VALID / CREATE_OVERRIDE / CREATE_AUTO /
// CREATE_IGNORE_CLIENT / CREATE_COLLISION). The id is generated by the DB
// (uuidv7); an EMPTY schedule override is stored as NULL (AD-5). The inventory
// number is AUTO-ASSIGNED in-SQL ('GEAR' || zero-padded nextval, atomic,
// monotonic — the client's inventory is ignored on create). When a manual edit
// consumed the generated sequence value, the INSERT trips the
// tools_inventory_number_key UNIQUE index and the insert is RETRIED with a
// FRESH nextval (bounded to maxInventoryNumberRetries, then the German
// collision 400). A nil attributes map is stored as '{}'. Duplicate-name
// semantics (coherent with the core's active-only case-insensitive guard): an
// EXACT name reuse of an archived row (invisible to the core guard) trips the
// DB UNIQUE constraint and is mapped to the German duplicate-name 400. A DB-level FK
// violation (the tool type or the schedule override vanished between the core
// check and this insert) is mapped to the German 400 — never a raw pg error /
// 500.
func (r *Repository) CreateTool(ctx context.Context, tool *core.Tool) (*core.Tool, error) {
	toolTypeID, err := parseToolTypeID(tool.ToolTypeID)
	if err != nil {
		return nil, err
	}
	schedule, err := parseOptionalUUID(tool.ScheduleID)
	if err != nil {
		return nil, err
	}
	attrs, err := marshalToolAttributes(tool.Attributes)
	if err != nil {
		return nil, err
	}
	params := CreateToolParams{
		Name:       tool.Name,
		ToolTypeID: toolTypeID,
		ScheduleID: schedule,
		Attributes: attrs,
	}
	for attempt := 0; attempt < maxInventoryNumberRetries; attempt++ {
		row, err := r.queries.CreateTool(ctx, params)
		if err == nil {
			return toolFromRow(row), nil
		}
		if isInventoryNumberCollision(err) {
			// The auto-assigned nextval collided with a manually-entered number
			// (a manual edit consumed a future sequence value). The next attempt
			// re-runs the INSERT, which computes a FRESH nextval in-SQL — no new
			// query, no client involvement.
			continue
		}
		if isUniqueViolation(err) {
			return nil, &core.InvalidToolError{Message: core.MsgToolNameTaken}
		}
		if isForeignKeyViolation(err) {
			// A race between the core's FK checks and this insert (the type
			// archived / the schedule override archived meanwhile) surfaces as
			// SQLSTATE 23503 — map it to the German 400, never a raw pg error /
			// 500.
			return nil, &core.InvalidToolError{Message: core.MsgToolReferencedGone}
		}
		return nil, err
	}
	// The bounded retry budget is exhausted — every generated number collided.
	return nil, &core.InvalidToolError{Message: core.MsgToolInventoryNumberCollision}
}

// UpdateTool replaces one ACTIVE tool's fields and refreshes updated_at
// (UPDATE_CLEAR_OVERRIDE / UPDATE_INVENTORY): an EMPTY schedule override CLEARS
// the stored override (schedule_id NULL → the tool inherits its type's default
// again, AD-5). The inventory number REPLACES the stored value (the core
// guarantees it is non-empty + bounded + unique case-insensitively among active
// tools). Returns core.ErrToolNotFound when the id does not exist OR the row is
// already archived (the SQL's `archived_at IS NULL` guard affects zero rows
// then). An EXACT new name already held by an ARCHIVED row trips the DB UNIQUE
// constraint and is mapped to the German duplicate-name 400; an EXACT inventory
// number already held by ANY row (active or archived — the Story 4.5 import
// backstop) trips the tools_inventory_number_key UNIQUE index and is mapped to
// the German duplicate-inventory 400; a DB-level FK violation is mapped to the
// German 400 — never a raw 500.
func (r *Repository) UpdateTool(ctx context.Context, tool *core.Tool) (*core.Tool, error) {
	uid, err := parseOptionalUUID(tool.ID)
	if err != nil {
		return nil, core.ErrToolNotFound
	}
	toolTypeID, err := parseToolTypeID(tool.ToolTypeID)
	if err != nil {
		return nil, err
	}
	schedule, err := parseOptionalUUID(tool.ScheduleID)
	if err != nil {
		return nil, err
	}
	attrs, err := marshalToolAttributes(tool.Attributes)
	if err != nil {
		return nil, err
	}
	row, err := r.queries.UpdateTool(ctx, UpdateToolParams{
		ID:              uid,
		Name:            tool.Name,
		ToolTypeID:      toolTypeID,
		ScheduleID:      schedule,
		InventoryNumber: tool.InventoryNumber,
		Attributes:      attrs,
	})
	if isUniqueViolation(err) {
		if isInventoryNumberCollision(err) {
			// An EXACT reuse of an inventory number (active OR archived — the
			// archived number stays taken) trips the UNIQUE index; the core's
			// case-insensitive active guard cannot see an archived row.
			return nil, &core.InvalidToolError{Message: core.MsgToolInventoryNumberTaken}
		}
		return nil, &core.InvalidToolError{Message: core.MsgToolNameTaken}
	}
	if isForeignKeyViolation(err) {
		// Same race as create: the type/override referenced by this update
		// vanished between the core check and this update → German 400.
		return nil, &core.InvalidToolError{Message: core.MsgToolReferencedGone}
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolNotFound
	}
	if err != nil {
		return nil, err
	}
	return toolFromUpdateRow(row), nil
}

// ArchiveTool soft-archives one tool (ARCHIVE): archived_at is set, the row
// leaves the active list. Returns core.ErrToolNotFound when the id does not
// exist OR the row is already archived.
func (r *Repository) ArchiveTool(ctx context.Context, id string) (*core.Tool, error) {
	uid, err := parseOptionalUUID(id)
	if err != nil {
		return nil, core.ErrToolNotFound
	}
	row, err := r.queries.ArchiveTool(ctx, uid)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, core.ErrToolNotFound
	}
	if err != nil {
		return nil, err
	}
	return toolFromArchiveRow(row), nil
}

// ListTools reads the ACTIVE tool catalog, oldest first, each with its tool
// type's display name (GET_LIST). Archived rows (archived_at IS NOT NULL)
// never appear; a tool WITHOUT an override reads back an empty ScheduleID
// (inherit the type default, AD-5).
func (r *Repository) ListTools(ctx context.Context) ([]*core.Tool, error) {
	rows, err := r.queries.ListTools(ctx)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return []*core.Tool{}, nil
	}
	out := make([]*core.Tool, 0, len(rows))
	for i := range rows {
		out = append(out, toolFromListRow(rows[i]))
	}
	return out, nil
}

// ToolExistsActive is the lean update-path existence check: it reports whether
// the id exists AND is still active, without fetching the row (which the
// update pre-check does not use). A missing, malformed or already-archived id
// reports false (the surface treats all three as non-existent, ErrToolNotFound).
func (r *Repository) ToolExistsActive(ctx context.Context, id string) (bool, error) {
	uid, err := parseToolTypeID(id)
	if err != nil {
		return false, nil
	}
	return r.queries.ToolExistsActive(ctx, uid)
}

// toolFromRow maps an sqlc tool row (already JOINed with its type name) to the
// domain value. The stored attributes jsonb is unmarshalled into the map
// (default '{}'); a malformed non-object value surfaces as a clear error rather
// than a silent drop. ArchivedAt is nil for an active row, set after
// soft-archive.
func toolFromRow(row CreateToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromListRow is the ListTools variant (ListToolsRow is a distinct sqlc
// struct with the identical shape).
func toolFromListRow(row ListToolsRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromUpdateRow is the UpdateTool variant (UpdateToolRow is a distinct
// sqlc struct with the identical shape).
func toolFromUpdateRow(row UpdateToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromArchiveRow is the ArchiveTool variant (ArchiveToolRow is a distinct
// sqlc struct with the identical shape).
func toolFromArchiveRow(row ArchiveToolRow) *core.Tool {
	return toolFromToolRow(
		row.ID, row.Name, row.ToolTypeID, row.ToolTypeName, row.ScheduleID,
		row.InventoryNumber, row.Attributes, row.ArchivedAt, row.CreatedAt, row.UpdatedAt,
	)
}

// toolFromToolRow is the shared mapping for the four identical sqlc row shapes.
func toolFromToolRow(
	id pgtype.UUID,
	name string,
	toolTypeID pgtype.UUID,
	toolTypeName string,
	scheduleID pgtype.UUID,
	inventoryNumber string,
	attributes []byte,
	archivedAt pgtype.Timestamptz,
	createdAt, updatedAt pgtype.Timestamptz,
) *core.Tool {
	tool := &core.Tool{
		ID:              id.String(),
		Name:            name,
		ToolTypeID:      toolTypeID.String(),
		ToolTypeName:    toolTypeName,
		ScheduleID:      scheduleID.String(),
		InventoryNumber: inventoryNumber,
		Attributes:      map[string]any{},
		CreatedAt:       createdAt.Time,
		UpdatedAt:       updatedAt.Time,
	}
	if archivedAt.Valid {
		t := archivedAt.Time
		tool.ArchivedAt = &t
	}
	if len(attributes) > 0 {
		var attrs map[string]any
		if err := json.Unmarshal(attributes, &attrs); err != nil {
			// The jsonb column rejects syntactically invalid JSON, so a
			// "malformed" value is a valid non-object shape written
			// out-of-band; surface it as a clear error, never a crash or a
			// silent data-loss read (Story 4.4 boundary).
			tool.Attributes = map[string]any{"_unparseable": string(attributes)}
			return tool
		}
		if attrs != nil {
			tool.Attributes = attrs
		}
	}
	return tool
}

// marshalToolAttributes encodes the attributes map for the jsonb column. A nil
// map (or an empty one) encodes as '{}' so the stored value is always a JSON
// object (the DB default when the column is omitted).
func marshalToolAttributes(attrs map[string]any) ([]byte, error) {
	if attrs == nil {
		return []byte("{}"), nil
	}
	raw, err := json.Marshal(attrs)
	if err != nil {
		return nil, err
	}
	if len(raw) == 0 || string(raw) == "null" {
		return []byte("{}"), nil
	}
	return raw, nil
}

// parseOptionalUUID parses a uuid FK that may be EMPTY (→ pgtype.UUID{} →
// SQL NULL), treating a malformed id as core.ErrToolNotFound. It is the
// generic sibling of parseToolTypeID — used for the tool surface's non-type FKs
// (the tool's own id and the optional schedule override) so the tool-type-named
// helper is only used where the FK is genuinely a tool type.
func parseOptionalUUID(id string) (pgtype.UUID, error) {
	if strings.TrimSpace(id) == "" {
		return pgtype.UUID{}, nil
	}
	var uid pgtype.UUID
	if err := uid.Scan(id); err != nil {
		return pgtype.UUID{}, core.ErrToolNotFound
	}
	return uid, nil
}

// isInventoryNumberCollision reports whether err is a UNIQUE-constraint
// violation on the tools_inventory_number_key index (Story 4-3b): the 
// auto-assigned number collided with a manually-entered one, or an update
// reused a number held by ANOTHER row (active or archived — the Story 4.5
// import backstop). The CreateTool retry loop branches on it; UpdateTool maps
// it to the German duplicate-inventory 400.
func isInventoryNumberCollision(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505" && pgErr.ConstraintName == "tools_inventory_number_key"
}

// Compile-time check: the repository satisfies the core ToolStore port.
var _ core.ToolStore = (*Repository)(nil)