// Package adapters hosts the outbound adapters of the User Directory & Auth
// hexagon (AD-1). They sit outside the hexagon and are wired at the
// composition root only. The PostgreSQL store is generated by sqlc into
// ./postgres from the queries in this directory.
package adapters
