// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID              pgtype.UUID        `json:"id"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	Operation       string             `json:"operation"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	OperationDetail pgtype.Text        `json:"operation_detail"`
	Severity        string             `json:"severity"`
}

type LoginAttempt struct {
	Email        string             `json:"email"`
	FailedCount  int32              `json:"failed_count"`
	LockoutUntil pgtype.Timestamptz `json:"lockout_until"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	TokenHash           string             `json:"token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	RecoveryTargetAdmin bool               `json:"recovery_target_admin"`
	ApprovedByUserID    pgtype.UUID        `json:"approved_by_user_id"`
	RequestedByUserID   pgtype.UUID        `json:"requested_by_user_id"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PermissionGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IsBaseRole  bool               `json:"is_base_role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PermissionGroupPermission struct {
	PermissionGroupID pgtype.UUID        `json:"permission_group_id"`
	PermissionID      pgtype.UUID        `json:"permission_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
	MustChangePassword         bool               `json:"must_change_password"`
}

type UserPermission struct {
	UserID       pgtype.UUID        `json:"user_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
}

type UserPermissionGroup struct {
	UserID            pgtype.UUID        `json:"user_id"`
	PermissionGroupID pgtype.UUID        `json:"permission_group_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
