// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
UPDATE login_attempts
SET failed_count = 0, lockout_until = NULL, updated_at = now()
WHERE email = $1
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, clearLoginAttempts, email)
	return err
}

const clearPendingEmail = `-- name: ClearPendingEmail :exec
UPDATE users
SET pending_email = NULL,
    updated_at    = now()
WHERE id = $1
`

// Clear a staged email change (pending_email -> NULL). Used by the Epic 2
// admin workflow when the staged email becomes the real email or the change is
// cancelled/rejected. Never touches the current email.
func (q *Queries) ClearPendingEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPendingEmail, id)
	return err
}

const clearUserPendingTotpSecret = `-- name: ClearUserPendingTotpSecret :exec
UPDATE users
SET pending_totp_secret_encrypted = NULL,
    pending_totp_expires_at       = NULL,
    updated_at                    = now()
WHERE id = $1
`

// Clear a pending TOTP enrollment after the confirm step (success or failure).
func (q *Queries) ClearUserPendingTotpSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserPendingTotpSecret, id)
	return err
}

const clearUserTotpSecret = `-- name: ClearUserTotpSecret :exec
UPDATE users
SET totp_secret_encrypted         = NULL,
    is_mfa_enabled                = false,
    pending_totp_secret_encrypted = NULL,
    pending_totp_expires_at       = NULL,
    updated_at                    = now()
WHERE id = $1
`

// Disable TOTP MFA (FR-4): clear the stored encrypted secret, the flag and any
// pending enrollment.
func (q *Queries) ClearUserTotpSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserTotpSecret, id)
	return err
}

const createRegisteredUser = `-- name: CreateRegisteredUser :one
INSERT INTO users (
    email,
    display_name,
    first_name,
    last_name,
    password_hash,
    state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending_approval'
)
RETURNING id, email, display_name, first_name, last_name, password_hash, state, is_mfa_enabled, totp_secret_encrypted, pending_totp_secret_encrypted, pending_totp_expires_at, attributes, created_at, updated_at, pending_email
`

type CreateRegisteredUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateRegisteredUserRow struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

func (q *Queries) CreateRegisteredUser(ctx context.Context, arg CreateRegisteredUserParams) (CreateRegisteredUserRow, error) {
	row := q.db.QueryRow(ctx, createRegisteredUser,
		arg.Email,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i CreateRegisteredUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.State,
		&i.IsMfaEnabled,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

// Atomic logout (NFR-S2): delete by the hashed token directly so there is no
// Get-then-Delete TOCTOU window.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

// Revoke every session of a user (NFR-S2). Used when MFA is disabled so all
// pre-existing sessions must re-authenticate (review finding 1.6-2).
func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const deleteSessionsByUserExcept = `-- name: DeleteSessionsByUserExcept :exec
DELETE FROM sessions
WHERE user_id = $1 AND token_hash <> $2
`

type DeleteSessionsByUserExceptParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

// Revoke all of a user's sessions except the one identified by the given token
// hash. Used when MFA is enabled so sessions issued before enrollment cannot
// bypass the new second factor (review finding 1.6-2).
func (q *Queries) DeleteSessionsByUserExcept(ctx context.Context, arg DeleteSessionsByUserExceptParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserExcept, arg.UserID, arg.TokenHash)
	return err
}

const getLoginAttempts = `-- name: GetLoginAttempts :one
SELECT email, failed_count, lockout_until, updated_at
FROM login_attempts
WHERE email = $1
`

func (q *Queries) GetLoginAttempts(ctx context.Context, email string) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, getLoginAttempts, email)
	var i LoginAttempt
	err := row.Scan(
		&i.Email,
		&i.FailedCount,
		&i.LockoutUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one

SELECT id, code, description
FROM permissions
WHERE code = $1
`

type GetPermissionByCodeRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
}

// User Directory & Auth module store (AD-2), generated into package postgres
// by sqlc. These are the building blocks the auth port resolves identity and
// permission sets from (AD-12: additive union of permission-group memberships
// + direct grants). Story 1.1 ships the toolchain plus the first queries;
// later stories extend this file and re-run `just sqlc-generate`.
func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i GetPermissionByCodeRow
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.created_at,
       u.email, u.display_name, u.first_name, u.last_name, u.state, u.is_mfa_enabled, u.password_hash, u.totp_secret_encrypted, u.pending_totp_secret_encrypted, u.pending_totp_expires_at, u.attributes, u.pending_email
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	TokenHash                  string             `json:"token_hash"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	PasswordHash               string             `json:"password_hash"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

// The session user snapshot carries the password hash so the authenticated
// user can be verified server-side on the change-password flow (FR-25), just
// as it carries the encrypted TOTP secret for MFA disable (FR-4). The hash is
// never serialized to clients (core.User.PasswordHash is json:"-").
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.State,
		&i.IsMfaEnabled,
		&i.PasswordHash,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.PendingEmail,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, first_name, last_name, password_hash, state, is_mfa_enabled, totp_secret_encrypted, pending_totp_secret_encrypted, pending_totp_expires_at, attributes, created_at, updated_at, pending_email
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.State,
		&i.IsMfaEnabled,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const incrementLoginAttempts = `-- name: IncrementLoginAttempts :exec
INSERT INTO login_attempts (email, failed_count, lockout_until)
VALUES ($1, 1, NULL)
ON CONFLICT (email) DO UPDATE SET
    failed_count  = LEAST(login_attempts.failed_count + 1, 10),
    lockout_until = CASE
        WHEN login_attempts.failed_count + 1 >= 4 THEN now() + interval '60 seconds'
        WHEN login_attempts.failed_count + 1 = 3 THEN now() + interval '30 seconds'
        ELSE NULL
    END,
    updated_at    = now()
`

// Atomic record of a failed login (FR-3): increments the per-email failure
// counter and sets the progressive lockout window when a threshold is crossed,
// in a single statement so concurrent attempts for the same email cannot lose
// updates. The counter is capped (LockoutMaxFailedCount = 10). Thresholds and
// durations mirror core.LockoutThreshold*/LockoutDuration*.
func (q *Queries) IncrementLoginAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementLoginAttempts, email)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_log (actor_user_id, operation)
VALUES ($1, $2)
`

type InsertAuditEventParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Operation   string      `json:"operation"`
}

// Append a row to the User-owned audit trail (NFR-O1/NFR-O2, spine table 11):
// actor_user_id + operation + created_at. Never records password values or
// other sensitive payloads. Written best-effort: a failure is logged, not
// rolled back into the triggering operation (availability).
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent, arg.ActorUserID, arg.Operation)
	return err
}

const listPermissionGroupsByUser = `-- name: ListPermissionGroupsByUser :many
SELECT pg.id, pg.name, pg.description, pg.is_base_role
FROM permission_groups pg
JOIN user_permission_groups upg ON upg.permission_group_id = pg.id
WHERE upg.user_id = $1
ORDER BY pg.name
`

type ListPermissionGroupsByUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	IsBaseRole  bool        `json:"is_base_role"`
}

func (q *Queries) ListPermissionGroupsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPermissionGroupsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPermissionGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionGroupsByUserRow
	for rows.Next() {
		var i ListPermissionGroupsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsBaseRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUser = `-- name: ListPermissionsByUser :many
SELECT DISTINCT p.code
FROM permissions p
WHERE p.id IN (
    SELECT pgp.permission_id
    FROM user_permission_groups upg
    JOIN permission_group_permissions pgp ON pgp.permission_group_id = upg.permission_group_id
    WHERE upg.user_id = $1
    UNION
    SELECT up.permission_id
    FROM user_permissions up
    WHERE up.user_id = $1
)
ORDER BY p.code
`

// Resolved permission set (AD-12): additive union of permission-group
// memberships plus direct grants. Deduplicated via DISTINCT.
func (q *Queries) ListPermissionsByUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPendingTotpSecret = `-- name: SetUserPendingTotpSecret :exec
UPDATE users
SET pending_totp_secret_encrypted = $2,
    pending_totp_expires_at       = $3,
    updated_at                    = now()
WHERE id = $1
`

type SetUserPendingTotpSecretParams struct {
	ID                         pgtype.UUID        `json:"id"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
}

// Persist a short-lived pending TOTP enrollment (FR-4): the freshly generated
// secret is stored ENCRYPTED at rest (NFR-S4) with an expiry. The confirm step
// validates a code against THIS server-issued secret.
func (q *Queries) SetUserPendingTotpSecret(ctx context.Context, arg SetUserPendingTotpSecretParams) error {
	_, err := q.db.Exec(ctx, setUserPendingTotpSecret, arg.ID, arg.PendingTotpSecretEncrypted, arg.PendingTotpExpiresAt)
	return err
}

const setUserTotpSecret = `-- name: SetUserTotpSecret :exec
UPDATE users
SET totp_secret_encrypted         = $2,
    is_mfa_enabled                = true,
    pending_totp_secret_encrypted = NULL,
    pending_totp_expires_at       = NULL,
    updated_at                    = now()
WHERE id = $1
`

type SetUserTotpSecretParams struct {
	ID                  pgtype.UUID `json:"id"`
	TotpSecretEncrypted pgtype.Text `json:"totp_secret_encrypted"`
}

// Enable TOTP MFA (FR-4): persist the AES-256-GCM encrypted shared secret and
// flip the is_mfa_enabled flag in one statement, clearing any pending
// enrollment. The plaintext secret is never stored (NFR-S4).
func (q *Queries) SetUserTotpSecret(ctx context.Context, arg SetUserTotpSecretParams) error {
	_, err := q.db.Exec(ctx, setUserTotpSecret, arg.ID, arg.TotpSecretEncrypted)
	return err
}

const stagePendingEmail = `-- name: StagePendingEmail :one
UPDATE users
SET pending_email = $2,
    updated_at    = now()
WHERE users.id = $1
  AND NOT EXISTS (
      SELECT 1 FROM users AS other
      WHERE other.id <> $1
        AND (lower(other.email) = lower($2) OR lower(other.pending_email) = lower($2))
  )
RETURNING id, email, display_name, first_name, last_name, password_hash, state, is_mfa_enabled, totp_secret_encrypted, pending_totp_secret_encrypted, pending_totp_expires_at, attributes, created_at, updated_at, pending_email
`

type StagePendingEmailParams struct {
	ID           pgtype.UUID `json:"id"`
	PendingEmail pgtype.Text `json:"pending_email"`
}

type StagePendingEmailRow struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

// Persist a STAGED email change (Story 2.1): the new address is stored in
// pending_email and the user stays ACTIVE on the current email until an admin
// approves the change (Epic 2 admin workflow).
//
// The UPDATE is conditional (review finding: TOCTOU email-collision guard): it
// only proceeds while NO OTHER account holds the address as its current email
// OR as an already-staged pending_email, compared case-insensitively with
// lower(). This closes the window where a registration racing between the
// core's GetUserByEmail pre-check and this UPDATE could leave pending_email
// equal to another account's email. A row that matches no other account is
// updated; otherwise zero rows are affected and the caller maps it to
// ErrEmailInUse.
func (q *Queries) StagePendingEmail(ctx context.Context, arg StagePendingEmailParams) (StagePendingEmailRow, error) {
	row := q.db.QueryRow(ctx, stagePendingEmail, arg.ID, arg.PendingEmail)
	var i StagePendingEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.State,
		&i.IsMfaEnabled,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
RETURNING id, email, display_name, first_name, last_name, password_hash, state, is_mfa_enabled, totp_secret_encrypted, pending_totp_secret_encrypted, pending_totp_expires_at, attributes, created_at, updated_at, pending_email
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

type UpdateUserPasswordRow struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

// Persist a new password hash for a user (FR-25). The plaintext password is
// never stored, logged or returned (NFR-O1/AD-13); only the Argon2id hash
// provided by the caller is written, with a fresh updated_at.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.State,
		&i.IsMfaEnabled,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name   = $2,
    last_name    = $3,
    display_name = $4,
    updated_at   = now()
WHERE id = $1
RETURNING id, email, display_name, first_name, last_name, password_hash, state, is_mfa_enabled, totp_secret_encrypted, pending_totp_secret_encrypted, pending_totp_expires_at, attributes, created_at, updated_at, pending_email
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DisplayName string      `json:"display_name"`
}

type UpdateUserProfileRow struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	DisplayName                string             `json:"display_name"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	PasswordHash               string             `json:"password_hash"`
	State                      string             `json:"state"`
	IsMfaEnabled               bool               `json:"is_mfa_enabled"`
	TotpSecretEncrypted        pgtype.Text        `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted pgtype.Text        `json:"pending_totp_secret_encrypted"`
	PendingTotpExpiresAt       pgtype.Timestamptz `json:"pending_totp_expires_at"`
	Attributes                 []byte             `json:"attributes"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PendingEmail               pgtype.Text        `json:"pending_email"`
}

// Persist the user's editable base data (first/last/display name, Story 2.1):
// changes take effect immediately for the authenticated user. Only the caller-
// supplied values are written; email and state are never touched here.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.State,
		&i.IsMfaEnabled,
		&i.TotpSecretEncrypted,
		&i.PendingTotpSecretEncrypted,
		&i.PendingTotpExpiresAt,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingEmail,
	)
	return i, err
}
