import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The G.E.A.R. documentation is organized by AUDIENCE, not by artifact type:
// every reader lands on the section that matches their role. The overview is
// for everyone (non-technical); the other four sections deepen from there.
// Generated pages (implementation/*, epics, status, screenshots) stay at their
// build-time paths but are surfaced inside the audience sections.
const docsSidebar: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        'intro',
        {type: 'doc', id: 'overview/what-is-gear'},
        {type: 'doc', id: 'management-overview'},
        {type: 'doc', id: 'overview/user-stories'},
      ],
    },
    {
      type: 'category',
      label: 'For End Users',
      items: [
        {type: 'doc', id: 'end-users/index'},
        {type: 'doc', id: 'end-users/dashboard'},
        {type: 'doc', id: 'end-users/inspections'},
        {type: 'doc', id: 'end-users/history'},
        {type: 'doc', id: 'end-users/account'},
      ],
    },
    {
      type: 'category',
      label: 'For Administrators',
      items: [
        {type: 'doc', id: 'administrators/index'},
        {type: 'doc', id: 'administrators/users-and-roles'},
        {type: 'doc', id: 'administrators/catalogue'},
        {type: 'doc', id: 'administrators/settings'},
        {type: 'doc', id: 'administrators/backups'},
        {type: 'doc', id: 'administrators/dsgvo'},
      ],
    },
    {
      type: 'category',
      label: 'For Developers',
      items: [
        {type: 'doc', id: 'developers/index'},
        {type: 'doc', id: 'implementation/modules'},
        {type: 'doc', id: 'implementation/api'},
        {type: 'doc', id: 'implementation/flows'},
        {type: 'doc', id: 'status'},
        {type: 'doc', id: 'epics/index'},
        {type: 'doc', id: 'screenshots'},
      ],
    },
    {
      type: 'category',
      label: 'For Architects',
      items: [
        {type: 'doc', id: 'architects/index'},
        {type: 'doc', id: 'planning/prd'},
        {type: 'doc', id: 'planning/architecture-spine'},
        {type: 'doc', id: 'planning/addendum'},
        {type: 'doc', id: 'planning/module-roadmap'},
        {type: 'doc', id: 'planning/ux-design'},
        {type: 'doc', id: 'planning/deployment-ionos'},
      ],
    },
  ],
  // The OpenAPI API reference is generated by `docusaurus gen-api-docs` into
  // docs/api/ (an autogenerated sidebar over that directory).
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

export default docsSidebar;