import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  // The OpenAPI API reference is generated by `docusaurus gen-api-docs` into
  // docs/api/ (an autogenerated sidebar over that directory).
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
